import { Controller, Post, Body, Get, Param, Patch, Res } from '@nestjs/common';
import type { Response } from 'express';
import { PayrollExecutionService } from './payroll-execution.service';
import { ApprovePayrollDto } from './dto/approve-payroll.dto';
import { RejectPayrollDto } from './dto/reject-payroll.dto';
import { SubmitForApprovalDto } from './dto/submit-for-approval.dto';
import { ManagerApprovalDto } from './dto/manager-approval.dto';
import { ManagerRejectDto } from './dto/manager-reject.dto';
import { FinanceApprovalDto } from './dto/finance-approval.dto';
import { FinanceRejectDto } from './dto/finance-reject.dto';
import { AutoGeneratePayrollDto } from './dto/auto-generate-payroll.dto';

@Controller('payroll-execution')
export class PayrollExecutionController {
  constructor(private readonly payrollService: PayrollExecutionService) {}

  @Post('initiate')
  async initiatePayroll(
    @Body('payrollPeriod') payrollPeriod: string,
    @Body('entity') entity: string,
    @Body('payrollSpecialistId') payrollSpecialistId: string,
  ) {
    return this.payrollService.initiatePayroll(
      new Date(payrollPeriod),
      entity,
      payrollSpecialistId,
    );
  }

  @Post('auto-generate')
  async autoGenerateDraftPayroll(@Body() autoGenerateDto: AutoGeneratePayrollDto) {
    if (autoGenerateDto.payrollPeriod) {
      return this.payrollService.autoGenerateDraftPayrollRun(
        new Date(autoGenerateDto.payrollPeriod),
        autoGenerateDto.entity,
        autoGenerateDto.payrollSpecialistId,
      );
    } else {
      return this.payrollService.autoGenerateDraftPayrollForCurrentPeriod(
        autoGenerateDto.entity,
        autoGenerateDto.payrollSpecialistId,
      );
    }
  }

  @Get('review')
  async getPayrollRunsForReview() {
    return this.payrollService.getPayrollRunsForReview();
  }

  @Get('manager/pending')
  async getPayrollRunsPendingManagerApproval() {
    return this.payrollService.getPayrollRunsPendingManagerApproval();
  }

  @Get('finance/pending')
  async getPayrollRunsPendingFinanceApproval() {
    return this.payrollService.getPayrollRunsPendingFinanceApproval();
  }

  @Get('review/:id')
  async getPayrollRunById(@Param('id') id: string) {
    return this.payrollService.getPayrollRunById(id);
  }

  @Patch('approve')
  async approvePayroll(@Body() approvePayrollDto: ApprovePayrollDto) {
    return this.payrollService.approvePayroll(
      approvePayrollDto.payrollRunId,
      approvePayrollDto.payrollSpecialistId,
    );
  }

  @Patch('reject')
  async rejectPayroll(@Body() rejectPayrollDto: RejectPayrollDto) {
    return this.payrollService.rejectPayroll(
      rejectPayrollDto.payrollRunId,
      rejectPayrollDto.rejectionReason,
      rejectPayrollDto.payrollSpecialistId,
    );
  }

  @Post('calculate/:id')
  async calculatePayroll(@Param('id') id: string) {
    return this.payrollService.calculatePayroll(id);
  }

  @Get('preview/:id')
  async getPayrollPreview(@Param('id') id: string) {
    return this.payrollService.getPayrollPreview(id);
  }

  @Post('submit-for-approval')
  async submitForManagerApproval(@Body() submitDto: SubmitForApprovalDto) {
    return this.payrollService.submitForManagerApproval(submitDto.payrollRunId);
  }

  @Patch('manager/approve')
  async managerApprove(@Body() approvalDto: ManagerApprovalDto) {
    return this.payrollService.managerApprove(
      approvalDto.payrollRunId,
      approvalDto.managerId,
    );
  }

  @Patch('manager/reject')
  async managerReject(@Body() rejectDto: ManagerRejectDto) {
    return this.payrollService.managerReject(
      rejectDto.payrollRunId,
      rejectDto.managerId,
      rejectDto.rejectionReason,
    );
  }

  @Patch('finance/approve')
  async financeApprove(@Body() approvalDto: FinanceApprovalDto) {
    return this.payrollService.financeApprove(
      approvalDto.payrollRunId,
      approvalDto.financeStaffId,
    );
  }

  @Patch('finance/reject')
  async financeReject(@Body() rejectDto: FinanceRejectDto) {
    return this.payrollService.financeReject(
      rejectDto.payrollRunId,
      rejectDto.financeStaffId,
      rejectDto.rejectionReason,
    );
  }

  @Post('payslips/generate/:id')
  async generatePayslips(@Param('id') id: string) {
    return this.payrollService.generatePayslips(id);
  }

  @Get('payslips/:id/pdf')
  async generatePayslipPDF(@Param('id') id: string, @Res() res: Response) {
    const pdfBuffer = await this.payrollService.generatePayslipPDF(id);
    
    res.set({
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="payslip-${id}.pdf"`,
      'Content-Length': pdfBuffer.length,
    });
    
    res.send(pdfBuffer);
  }
}
