import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import PDFDocument from 'pdfkit';
import { payrollRuns } from './models/payrollRuns.schema';
import { PayRollStatus, PayRollPaymentStatus, BankStatus, PaySlipPaymentStatus } from './enums/payroll-execution-enum';
import { EmployeeProfile } from '../employee-profile/models/employee-profile.schema';
import { payGrade } from '../payroll-configuration/models/payGrades.schema';
import { allowance } from '../payroll-configuration/models/allowance.schema';
import { taxRules } from '../payroll-configuration/models/taxRules.schema';
import { insuranceBrackets } from '../payroll-configuration/models/insuranceBrackets.schema';
import { payrollPolicies } from '../payroll-configuration/models/payrollPolicies.schema';
import { employeePayrollDetails } from './models/employeePayrollDetails.schema';
import { paySlip } from './models/payslip.schema';
import { ConfigStatus, PolicyType, Applicability } from '../payroll-configuration/enums/payroll-configuration-enums';
import { EmployeeStatus, WorkType } from '../employee-profile/enums/employee-profile.enums';

@Injectable()
export class PayrollExecutionService {
  constructor(
    @InjectModel(payrollRuns.name) private payrollRunsModel: Model<payrollRuns>,
    @InjectModel(EmployeeProfile.name) private employeeProfileModel: Model<EmployeeProfile>,
    @InjectModel(payGrade.name) private payGradeModel: Model<payGrade>,
    @InjectModel(allowance.name) private allowanceModel: Model<allowance>,
    @InjectModel(taxRules.name) private taxRulesModel: Model<taxRules>,
    @InjectModel(insuranceBrackets.name) private insuranceBracketsModel: Model<insuranceBrackets>,
    @InjectModel(payrollPolicies.name) private payrollPoliciesModel: Model<payrollPolicies>,
    @InjectModel(employeePayrollDetails.name) private employeePayrollDetailsModel: Model<employeePayrollDetails>,
    @InjectModel(paySlip.name) private paySlipModel: Model<paySlip>,
  ) {}

  async initiatePayroll(
    payrollPeriod: Date,
    entity: string,
    payrollSpecialistId: string,
  ): Promise<payrollRuns> {
    const year = payrollPeriod.getFullYear();
    const month = String(payrollPeriod.getMonth() + 1).padStart(2, '0');
    
    const lastRun = await this.payrollRunsModel
      .findOne({ runId: new RegExp(^PR-${year}-${month}-) })
      .sort({ runId: -1 })
      .exec();
    
    const sequence = lastRun 
      ? parseInt(lastRun.runId.split('-')[3] || '0', 10) + 1 
      : 1;
    const runId = PR-${year}-${month}-${String(sequence).padStart(4, '0')};

    const payrollRun = new this.payrollRunsModel({
      runId,
      payrollPeriod,
      status: PayRollStatus.DRAFT,
      entity,
      employees: 0,
      exceptions: 0,
      totalnetpay: 0,
      payrollSpecialistId: new Types.ObjectId(payrollSpecialistId) as any,
      paymentStatus: PayRollPaymentStatus.PENDING,
      payrollManagerId: new Types.ObjectId(payrollSpecialistId) as any, // Set initially to specialist, will be updated when manager approves
    });

    return payrollRun.save();
  }

  async autoGenerateDraftPayrollRun(
    payrollPeriod: Date,
    entity: string,
    payrollSpecialistId: string,
  ): Promise<payrollRuns> {
    const year = payrollPeriod.getFullYear();
    const month = payrollPeriod.getMonth() + 1;

    // Check if a payroll run already exists for this period
    const existingRun = await this.payrollRunsModel
      .findOne({
        payrollPeriod: {
          $gte: new Date(year, month - 1, 1),
          $lt: new Date(year, month, 1),
        },
        entity,
      })
      .exec();

    if (existingRun) {
      throw new BadRequestException(
        A payroll run already exists for ${year}-${String(month).padStart(2, '0')}. Run ID: ${existingRun.runId},
      );
    }

    // Generate the draft payroll run
    return this.initiatePayroll(payrollPeriod, entity, payrollSpecialistId);
  }

  async autoGenerateDraftPayrollForCurrentPeriod(
    entity: string,
    payrollSpecialistId: string,
  ): Promise<payrollRuns> {
    // Get the last day of the current month
    const now = new Date();
    const lastDayOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0);

    return this.autoGenerateDraftPayrollRun(lastDayOfMonth, entity, payrollSpecialistId);
  }

  async getPayrollRunsForReview(): Promise<payrollRuns[]> {
    return this.payrollRunsModel
      .find({
        status: PayRollStatus.DRAFT,
      })
      .populate('payrollSpecialistId')
      .sort({ createdAt: -1 })
      .exec();
  }

  async getPayrollRunsPendingManagerApproval(): Promise<payrollRuns[]> {
    return this.payrollRunsModel
      .find({
        status: { $in: [PayRollStatus.DRAFT, PayRollStatus.UNDER_REVIEW] },
      })
      .populate('payrollSpecialistId')
      .sort({ createdAt: -1 })
      .exec();
  }

  async getPayrollRunsPendingFinanceApproval(): Promise<payrollRuns[]> {
    return this.payrollRunsModel
      .find({
        status: { $in: [PayRollStatus.UNDER_REVIEW, PayRollStatus.PENDING_FINANCE_APPROVAL] },
      })
      .populate('payrollSpecialistId')
      .populate('payrollManagerId')
      .sort({ createdAt: -1 })
      .exec();
  }

  async getPayrollRunById(payrollRunId: string): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel
      .findById(payrollRunId)
      .populate('payrollSpecialistId')
      .populate('payrollManagerId')
      .populate('financeStaffId')
      .exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    return payrollRun;
  }

  async approvePayroll(
    payrollRunId: string,
    payrollSpecialistId: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.DRAFT) {
      throw new BadRequestException(
        Cannot approve payroll run with status: ${payrollRun.status}. Only DRAFT payroll runs can be approved.,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'approve payroll run');

    payrollRun.status = PayRollStatus.UNDER_REVIEW;
    payrollRun.managerApprovalDate = new Date();
    payrollRun.payrollManagerId = new Types.ObjectId(payrollSpecialistId) as any;

    return payrollRun.save();
  }

  async rejectPayroll(
    payrollRunId: string,
    rejectionReason: string,
    payrollSpecialistId: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.DRAFT) {
      throw new BadRequestException(
        Cannot reject payroll run with status: ${payrollRun.status}. Only DRAFT payroll runs can be rejected.,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'reject payroll run');

    payrollRun.status = PayRollStatus.REJECTED;
    payrollRun.rejectionReason = rejectionReason;

    return payrollRun.save();
  }

  async submitForManagerApproval(payrollRunId: string): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.DRAFT) {
      throw new BadRequestException(
        Cannot submit payroll run with status: ${payrollRun.status}. Only DRAFT payroll runs can be submitted for approval.,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'submit payroll run for approval');

    if (payrollRun.employees === 0) {
      throw new BadRequestException('Cannot submit payroll run with no employees. Please calculate payroll first.');
    }

    payrollRun.status = PayRollStatus.UNDER_REVIEW;
    return payrollRun.save();
  }

  async managerApprove(
    payrollRunId: string,
    managerId: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.UNDER_REVIEW) {
      throw new BadRequestException(
        Cannot approve payroll run with status: ${payrollRun.status}. Only payroll runs UNDER_REVIEW can be approved by manager.,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'approve payroll run as manager');

    payrollRun.status = PayRollStatus.PENDING_FINANCE_APPROVAL;
    payrollRun.managerApprovalDate = new Date();
    payrollRun.payrollManagerId = new Types.ObjectId(managerId) as any;

    return payrollRun.save();
  }
}