import { Injectable, NotFoundException, BadRequestException,ConflictException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import PDFDocument from 'pdfkit';
import { payrollRuns } from './models/payrollRuns.schema';
import { PayRollStatus, PayRollPaymentStatus, BankStatus, PaySlipPaymentStatus } from './enums/payroll-execution-enum';
import { EmployeeProfile } from '../employee-profile/models/employee-profile.schema';
import { payGrade } from '../payroll-configuration/models/payGrades.schema';
import { allowance } from '../payroll-configuration/models/allowance.schema';
import { taxRules } from '../payroll-configuration/models/taxRules.schema';
import { insuranceBrackets } from '../payroll-configuration/models/insuranceBrackets.schema';
import { payrollPolicies } from '../payroll-configuration/models/payrollPolicies.schema';
import { employeePayrollDetails } from './models/employeePayrollDetails.schema';
import { paySlip } from './models/payslip.schema';
import { ConfigStatus, PolicyType, Applicability } from '../payroll-configuration/enums/payroll-configuration-enums';
import { EmployeeStatus, WorkType } from '../employee-profile/enums/employee-profile.enums';
import { employeeSigningBonus } from './models/EmployeeSigningBonus.schema';
import { EditSigningBonusDto } from './dto/EmployeeSigningBonusEdit.dto';
import { ApproveSigningBonusDto } from './dto/EmployeeSigningBonusApprove.dto';
import { RejectSigningBonusDto } from './dto/EmployeeSigningBonusReject.dto';
import { EmployeeTerminationResignation } from './models/EmployeeTerminationResignation.schema';
import { EmployeeTerminationResignationEditDto } from './dto/EmployeeTerminationResignationEdit.dto';
import { EmployeeTerminationResignationApproveDto } from './dto/EmployeeTerminationResignationApprove.dto';
import { EmployeeTerminationResignationRejectDto } from './dto/EmployeeTerminationResignationReject.dto';
import { EditPayrollInitiationDto } from './dto/edit-payroll-initiation.dto';
import { InitiatePayrollDto2 } from './dto/initiate-payroll2.dto';
import { ValidatePeriodDto } from './dto/validate-period.dto';

@Injectable()
export class PayrollExecutionService {
  constructor(
    @InjectModel(payrollRuns.name) private payrollRunsModel: Model<payrollRuns>,
    @InjectModel(EmployeeProfile.name) private employeeProfileModel: Model<EmployeeProfile>,
    @InjectModel(payGrade.name) private payGradeModel: Model<payGrade>,
    @InjectModel(allowance.name) private allowanceModel: Model<allowance>,
    @InjectModel(taxRules.name) private taxRulesModel: Model<taxRules>,
    @InjectModel(insuranceBrackets.name) private insuranceBracketsModel: Model<insuranceBrackets>,
    @InjectModel(payrollPolicies.name) private payrollPoliciesModel: Model<payrollPolicies>,
    @InjectModel(employeePayrollDetails.name) private employeePayrollDetailsModel: Model<employeePayrollDetails>,
    @InjectModel(paySlip.name) private paySlipModel: Model<paySlip>,
  ) {}

  async initiatePayroll(
    payrollPeriod: Date,
    entity: string,
    payrollSpecialistId: string,
  ): Promise<payrollRuns> {
    const year = payrollPeriod.getFullYear();
    const month = payrollPeriod.getMonth() + 1;
    
    // Check if a payroll run already exists for this period and entity
    const existingRun = await this.payrollRunsModel
      .findOne({
        payrollPeriod: {
          $gte: new Date(year, month - 1, 1),
          $lt: new Date(year, month, 1),
        },
        entity,
      })
      .exec();

    if (existingRun) {
      throw new BadRequestException(
        `A payroll run already exists for ${year}-${String(month).padStart(2, '0')} for entity ${entity}. Only one payroll run per month is allowed. Run ID: ${existingRun.runId}`,
      );
    }

    const monthStr = String(month).padStart(2, '0');
    const lastRun = await this.payrollRunsModel
      .findOne({ runId: new RegExp(`^PR-${year}-${monthStr}-`) })
      .sort({ runId: -1 })
      .exec();
    
    const sequence = lastRun 
      ? parseInt(lastRun.runId.split('-')[3] || '0', 10) + 1 
      : 1;
    const runId = `PR-${year}-${monthStr}-${String(sequence).padStart(4, '0')}`;

    const payrollRun = new this.payrollRunsModel({
      runId,
      payrollPeriod,
      status: PayRollStatus.DRAFT,
      entity,
      employees: 0,
      exceptions: 0,
      totalnetpay: 0,
      payrollSpecialistId: new Types.ObjectId(payrollSpecialistId) as any,
      paymentStatus: PayRollPaymentStatus.PENDING,
      payrollManagerId: new Types.ObjectId(payrollSpecialistId) as any, // Set initially to specialist, will be updated when manager approves
    });

    return payrollRun.save();
  }

  async autoGenerateDraftPayrollRun(
    payrollPeriod: Date,
    entity: string,
    payrollSpecialistId: string,
  ): Promise<payrollRuns> {
    const year = payrollPeriod.getFullYear();
    const month = payrollPeriod.getMonth() + 1;

    // Check if a payroll run already exists for this period and entity
    const existingRun = await this.payrollRunsModel
      .findOne({
        payrollPeriod: {
          $gte: new Date(year, month - 1, 1),
          $lt: new Date(year, month, 1),
        },
        entity,
      })
      .exec();

    if (existingRun) {
      throw new BadRequestException(
        `A payroll run already exists for ${year}-${String(month).padStart(2, '0')} for entity ${entity}. Only one payroll run per month is allowed. Run ID: ${existingRun.runId}`,
      );
    }

    // Create the draft payroll run directly (don't call initiatePayroll to avoid double-checking)
    const monthStr = String(month).padStart(2, '0');
    const lastRun = await this.payrollRunsModel
      .findOne({ runId: new RegExp(`^PR-${year}-${monthStr}-`) })
      .sort({ runId: -1 })
      .exec();
    
    const sequence = lastRun 
      ? parseInt(lastRun.runId.split('-')[3] || '0', 10) + 1 
      : 1;
    const runId = `PR-${year}-${monthStr}-${String(sequence).padStart(4, '0')}`;

    const payrollRun = new this.payrollRunsModel({
      runId,
      payrollPeriod,
      status: PayRollStatus.DRAFT,
      entity,
      employees: 0,
      exceptions: 0,
      totalnetpay: 0,
      payrollSpecialistId: new Types.ObjectId(payrollSpecialistId) as any,
      paymentStatus: PayRollPaymentStatus.PENDING,
      payrollManagerId: new Types.ObjectId(payrollSpecialistId) as any,
    });

    return payrollRun.save();
  }

  async autoGenerateDraftPayrollForCurrentPeriod(
    entity: string,
    payrollSpecialistId: string,
  ): Promise<payrollRuns> {
    // Get the last day of the current month
    const now = new Date();
    const lastDayOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0);

    return this.autoGenerateDraftPayrollRun(lastDayOfMonth, entity, payrollSpecialistId);
  }

  async getPayrollRunsForReview(): Promise<payrollRuns[]> {
    return this.payrollRunsModel
      .find({
        status: PayRollStatus.DRAFT,
      })
      .populate('payrollSpecialistId')
      .sort({ createdAt: -1 })
      .exec();
  }

  async getPayrollRunsPendingManagerApproval(): Promise<payrollRuns[]> {
    return this.payrollRunsModel
      .find({
        status: PayRollStatus.UNDER_REVIEW,
      })
      .populate('payrollSpecialistId')
      .sort({ createdAt: -1 })
      .exec();
  }

  async getPayrollRunsPendingFinanceApproval(): Promise<payrollRuns[]> {
    return this.payrollRunsModel
      .find({
        status: { $in: [PayRollStatus.UNDER_REVIEW, PayRollStatus.PENDING_FINANCE_APPROVAL] },
      })
      .populate('payrollSpecialistId')
      .populate('payrollManagerId')
      .sort({ createdAt: -1 })
      .exec();
  }

  async getApprovedAndLockedRuns(): Promise<payrollRuns[]> {
    return this.payrollRunsModel
      .find({
        status: { $in: [PayRollStatus.APPROVED, PayRollStatus.LOCKED] },
      })
      .populate('payrollSpecialistId')
      .populate('payrollManagerId')
      .populate('financeStaffId')
      .sort({ createdAt: -1 })
      .exec();
  }

  async getPayrollRunById(payrollRunId: string): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel
      .findById(payrollRunId)
      .populate('payrollSpecialistId')
      .populate('payrollManagerId')
      .populate('financeStaffId')
      .exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    return payrollRun;
  }

  async approvePayroll(
    payrollRunId: string,
    payrollSpecialistId: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.DRAFT) {
      throw new BadRequestException(
        `Cannot approve payroll run with status: ${payrollRun.status}. Only DRAFT payroll runs can be approved.`,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'approve payroll run');

    // Validate that payroll has been calculated (has employees)
    if (payrollRun.employees === 0) {
      throw new BadRequestException('Cannot approve payroll run with no employees. Please calculate payroll first.');
    }

    // Specialist approves: DRAFT → UNDER_REVIEW
    // Manager fields will be set when manager approves
    payrollRun.status = PayRollStatus.UNDER_REVIEW;

    return payrollRun.save();
  }

  async rejectPayroll(
    payrollRunId: string,
    rejectionReason: string,
    payrollSpecialistId: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.DRAFT) {
      throw new BadRequestException(
        `Cannot reject payroll run with status: ${payrollRun.status}. Only DRAFT payroll runs can be rejected.`,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'reject payroll run');

    payrollRun.status = PayRollStatus.REJECTED;
    payrollRun.rejectionReason = rejectionReason;

    return payrollRun.save();
  }

  async managerApprove(
    payrollRunId: string,
    managerId: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.UNDER_REVIEW) {
      throw new BadRequestException(
        `Cannot approve payroll run with status: ${payrollRun.status}. Only payroll runs UNDER_REVIEW can be approved by manager.`,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'approve payroll run as manager');

    payrollRun.status = PayRollStatus.PENDING_FINANCE_APPROVAL;
    payrollRun.managerApprovalDate = new Date();
    payrollRun.payrollManagerId = new Types.ObjectId(managerId) as any;

    return payrollRun.save();
  }

  async managerReject(
    payrollRunId: string,
    managerId: string,
    rejectionReason: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.UNDER_REVIEW) {
      throw new BadRequestException(
        `Cannot reject payroll run with status: ${payrollRun.status}. Only payroll runs UNDER_REVIEW can be rejected by manager.`,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'reject payroll run as manager');

    payrollRun.status = PayRollStatus.REJECTED;
    payrollRun.rejectionReason = rejectionReason;
    payrollRun.payrollManagerId = new Types.ObjectId(managerId) as any;

    return payrollRun.save();
  }

  async financeApprove(
    payrollRunId: string,
    financeStaffId: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.PENDING_FINANCE_APPROVAL) {
      throw new BadRequestException(
        `Cannot approve payroll run with status: ${payrollRun.status}. Only payroll runs PENDING_FINANCE_APPROVAL can be approved by finance.`,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'approve payroll run as finance');

    // Additional validation: Ensure manager has approved
    if (!payrollRun.managerApprovalDate || !payrollRun.payrollManagerId) {
      throw new BadRequestException(
        'Cannot approve payroll run. Manager approval is required before finance approval.',
      );
    }

    // Additional validation: Check for critical irregularities
    const employeeDetails = await this.employeePayrollDetailsModel
      .find({ payrollRunId: payrollRun._id })
      .exec();

    const criticalIssues = employeeDetails.filter(
      (detail) =>
        detail.netSalary < 0 ||
        detail.bankStatus === BankStatus.MISSING ||
        (detail.exceptions && detail.exceptions.includes('Negative net pay')),
    );

    if (criticalIssues.length > 0) {
      throw new BadRequestException(
        `Cannot approve payroll run. Found ${criticalIssues.length} employee(s) with critical issues (negative net pay or missing bank accounts). Please resolve these issues before approval.`,
      );
    }

    payrollRun.status = PayRollStatus.APPROVED;
    payrollRun.paymentStatus = PayRollPaymentStatus.PENDING;
    payrollRun.financeApprovalDate = new Date();
    payrollRun.financeStaffId = new Types.ObjectId(financeStaffId) as any;

    return payrollRun.save();
  }

  async financeReject(
    payrollRunId: string,
    financeStaffId: string,
    rejectionReason: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.PENDING_FINANCE_APPROVAL) {
      throw new BadRequestException(
        `Cannot reject payroll run with status: ${payrollRun.status}. Only payroll runs PENDING_FINANCE_APPROVAL can be rejected by finance.`,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'reject payroll run as finance');

    payrollRun.status = PayRollStatus.REJECTED;
    payrollRun.rejectionReason = rejectionReason;
    payrollRun.financeStaffId = new Types.ObjectId(financeStaffId) as any;

    return payrollRun.save();
  }

  /**
   * Helper method to check if a payroll run is locked
   */
  private isPayrollLocked(payrollRun: payrollRuns): boolean {
    return payrollRun.status === PayRollStatus.LOCKED;
  }

  /**
   * Helper method to validate that payroll run is not locked before making changes
   */
  private validatePayrollNotLocked(payrollRun: payrollRuns, operation: string): void {
    if (this.isPayrollLocked(payrollRun)) {
      throw new BadRequestException(
        `Cannot ${operation}. Payroll run ${payrollRun.runId} is locked and cannot be modified. Please unlock it first if you need to make changes.`,
      );
    }
  }

  /**
   * Lock a finalized payroll run to prevent unauthorized retroactive changes
   * Only Payroll Managers can lock payroll runs
   */
  async lockPayrollRun(
    payrollRunId: string,
    managerId: string,
    lockReason: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    // managerId may come from different auth providers; ensure it's a non-empty string
    if (!managerId || typeof managerId !== 'string' || managerId.trim().length === 0) {
      throw new BadRequestException('Manager identity missing or invalid');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    // Only APPROVED payroll runs can be locked (finalized payrolls)
    if (payrollRun.status !== PayRollStatus.APPROVED) {
      throw new BadRequestException(
        `Cannot lock payroll run with status: ${payrollRun.status}. Only APPROVED payroll runs can be locked.`,
      );
    }

    // Check if already locked
    if (this.isPayrollLocked(payrollRun)) {
      throw new BadRequestException(
        `Payroll run ${payrollRun.runId} is already locked.`,
      );
    }

    payrollRun.status = PayRollStatus.LOCKED;
    // Store lock reason in unlockReason field (reusing existing field)
    payrollRun.unlockReason = `LOCKED: ${lockReason}`;

    return payrollRun.save();
  }

 
  async unlockPayrollRun(
    payrollRunId: string,
    managerId: string,
    unlockReason: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    if (!Types.ObjectId.isValid(managerId)) {
      throw new BadRequestException('Invalid manager ID');
    }

    // Validate unlock reason is substantial (at least 20 characters)
    if (!unlockReason || unlockReason.trim().length < 20) {
      throw new BadRequestException(
        'Unlock reason must be at least 20 characters to properly document the exceptional circumstances requiring this unlock.',
      );
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    // Only LOCKED payroll runs can be unlocked
    if (!this.isPayrollLocked(payrollRun)) {
      throw new BadRequestException(
        `Cannot unlock payroll run with status: ${payrollRun.status}. Only LOCKED payroll runs can be unlocked.`,
      );
    }

    // Return to APPROVED status to allow modifications
    payrollRun.status = PayRollStatus.APPROVED;
    // Store the unlock reason with timestamp for audit trail
    const timestamp = new Date().toISOString();
    payrollRun.unlockReason = `[UNLOCKED ${timestamp}] ${unlockReason}`;

    return payrollRun.save();
  }

  async calculatePayroll(payrollRunId: string): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.DRAFT) {
      throw new BadRequestException(
        `Cannot calculate payroll for run with status: ${payrollRun.status}. Only DRAFT payroll runs can be calculated.`,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'calculate payroll');

    // Get all active employees for the payroll period
    const payrollPeriodStart = new Date(payrollRun.payrollPeriod);
    payrollPeriodStart.setDate(1); // First day of the month
    
    // Set end to last day of the month
    const payrollPeriodEnd = new Date(payrollRun.payrollPeriod);
    payrollPeriodEnd.setMonth(payrollPeriodEnd.getMonth() + 1);
    payrollPeriodEnd.setDate(0); // Last day of previous month

    const activeEmployees = await this.employeeProfileModel
      .find({
        status: EmployeeStatus.ACTIVE,
        dateOfHire: { $lte: payrollPeriodEnd },
        $or: [
          { contractEndDate: { $gte: payrollPeriodStart } },
          { contractEndDate: { $exists: false } },
        ],
      })
      .populate('payGradeId')
      .exec();

    // Get all configuration rules (don't filter by status - use what's available)
    const [approvedAllowances, approvedTaxRules, approvedInsuranceBrackets] = await Promise.all([
      this.allowanceModel.find({}).exec(),
      this.taxRulesModel.find({}).exec(),
      this.insuranceBracketsModel.find({}).exec(),
    ]);

    const approvedPolicies = await this.payrollPoliciesModel
      .find({
        effectiveDate: { $lte: payrollPeriodEnd },
        policyType: PolicyType.DEDUCTION, // Only statutory deduction policies
      })
      .exec();

    let totalNetPay = 0;
    let totalExceptions = 0;
    const employeePayrollDetailsList: any[] = [];

    // Calculate payroll for each employee
    for (const employee of activeEmployees) {
      try {
        const calculation = await this.calculateEmployeePayroll(
          employee,
          payrollRun._id as Types.ObjectId,
          approvedAllowances,
          approvedTaxRules,
          approvedInsuranceBrackets,
          approvedPolicies,
          payrollPeriodStart,
          payrollPeriodEnd,
        );

        employeePayrollDetailsList.push(calculation.employeePayrollDetail.toObject());
        totalNetPay += calculation.netPay;
        if (calculation.exceptions) {
          totalExceptions++;
        }
      } catch (error: any) {
        totalExceptions++;
        // Create a payroll detail with exception
        const exceptionDetail = {
          employeeId: new Types.ObjectId(employee.id || employee._id),
          payrollRunId: payrollRun._id,
          baseSalary: 0,
          allowances: 0,
          deductions: 0,
          netSalary: 0,
          netPay: 0,
          bankStatus: BankStatus.MISSING,
          exceptions: `Calculation error: ${error?.message || 'Unknown error'}`,
        };
        employeePayrollDetailsList.push(exceptionDetail);
      }
    }

    // Save all employee payroll details
    if (employeePayrollDetailsList.length > 0) {
      await this.employeePayrollDetailsModel.insertMany(employeePayrollDetailsList);
    }

    // Update payroll run totals
    payrollRun.employees = activeEmployees.length;
    payrollRun.exceptions = totalExceptions;
    payrollRun.totalnetpay = totalNetPay;

    return payrollRun.save();
  }

  async getPayrollPreview(payrollRunId: string): Promise<any> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel
      .findById(payrollRunId)
      .populate('payrollSpecialistId')
      .exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    // Get all employee payroll details for this run
    const employeeDetails = await this.employeePayrollDetailsModel
      .find({ payrollRunId: payrollRun._id })
      .populate('employeeId')
      .sort({ netPay: -1 })
      .exec();

    // Calculate summary statistics
    const totalEmployees = employeeDetails.length;
    const employeesWithExceptions = employeeDetails.filter((d) => d.exceptions).length;
    const totalBaseSalary = employeeDetails.reduce((sum, d) => sum + d.baseSalary, 0);
    const totalAllowances = employeeDetails.reduce((sum, d) => sum + d.allowances, 0);
    const totalDeductions = employeeDetails.reduce((sum, d) => sum + d.deductions, 0);
    const totalNetPay = employeeDetails.reduce((sum, d) => sum + d.netPay, 0);
    const employeesWithMissingBank = employeeDetails.filter(
      (d) => d.bankStatus === BankStatus.MISSING,
    ).length;
    const employeesWithNegativePay = employeeDetails.filter((d) => d.netSalary < 0).length;

    // Format employee details for preview
    const employeeList = employeeDetails.map((detail) => {
      const employee = detail.employeeId as any;
      return {
        employeePayrollDetailId: detail._id,
        employeeId: detail.employeeId,
        employeeNumber: employee?.employeeNumber || 'N/A',
        employeeName: employee
          ? `${employee.firstName || ''} ${employee.lastName || ''}`.trim()
          : 'N/A',
        baseSalary: detail.baseSalary,
        allowances: detail.allowances,
        deductions: detail.deductions,
        netSalary: detail.netSalary,
        netPay: detail.netPay,
        bankStatus: detail.bankStatus,
        exceptions: detail.exceptions,
        hasIrregularities: !!detail.exceptions || detail.netSalary < 0 || detail.bankStatus === BankStatus.MISSING,
      };
    });

    return {
      payrollRun: {
        runId: payrollRun.runId,
        payrollPeriod: payrollRun.payrollPeriod,
        status: payrollRun.status,
        entity: payrollRun.entity,
      
      },
      summary: {
        totalEmployees,
        employeesWithExceptions,
        employeesWithMissingBank,
        employeesWithNegativePay,
        totalBaseSalary,
        totalAllowances,
        totalDeductions,
        totalNetPay,
      },
      employees: employeeList,
      irregularities: employeeList.filter((e) => e.hasIrregularities),
    };
  }

  private async calculateEmployeePayroll(
    employee: any,
    payrollRunId: Types.ObjectId,
    approvedAllowances: allowance[],
    approvedTaxRules: taxRules[],
    approvedInsuranceBrackets: insuranceBrackets[],
    approvedPolicies: payrollPolicies[],
    payrollPeriodStart: Date,
    payrollPeriodEnd: Date,
  ): Promise<{
    employeePayrollDetail: any;
    netPay: number;
    exceptions?: string;
  }> {
    const irregularities: string[] = [];
    const employeeId = new Types.ObjectId(employee.id || (employee as any)._id);
    
    // Get base salary from pay grade
    let baseSalary = 0;
    if (employee.payGradeId) {
      if (typeof employee.payGradeId === 'object' && employee.payGradeId.baseSalary) {
        // Already populated
        baseSalary = employee.payGradeId.baseSalary;
      } else {
        // Need to fetch
        const payGradeDoc = await this.payGradeModel.findById(employee.payGradeId).exec();
        if (payGradeDoc) {
          baseSalary = payGradeDoc.baseSalary || 0;
        }
      }
    }

    if (baseSalary === 0) {
      irregularities.push('No pay grade assigned or pay grade has 0 salary');
    }

    // Calculate proration for mid-month hires and terminations
    const prorationInfo = this.calculateProration(
      employee.dateOfHire,
      employee.contractEndDate,
      employee.status,
      employee.statusEffectiveFrom,
      payrollPeriodStart,
      payrollPeriodEnd,
    );

    // Apply proration to base salary
    if (prorationInfo.isProrated) {
      baseSalary = baseSalary * prorationInfo.prorationFactor;
      irregularities.push(
        `Prorated salary: ${prorationInfo.daysWorked} days worked out of ${prorationInfo.totalDays} days (${(prorationInfo.prorationFactor * 100).toFixed(1)}%)`,
      );
    }

    // Check for sudden salary spike (compare with previous payroll run)
    const previousPayroll = await this.employeePayrollDetailsModel
      .findOne({ employeeId })
      .sort({ createdAt: -1 })
      .exec();

    if (previousPayroll && previousPayroll.baseSalary > 0) {
      const salaryIncrease = ((baseSalary - previousPayroll.baseSalary) / previousPayroll.baseSalary) * 100;
      if (salaryIncrease > 20) {
        irregularities.push(`Sudden salary spike detected: ${salaryIncrease.toFixed(1)}% increase from previous period`);
      }
    }

    // Calculate allowances (sum of all approved allowances) - also prorated
    let totalAllowances = approvedAllowances.reduce((sum, a) => sum + (a.amount || 0), 0);
    if (prorationInfo.isProrated) {
      totalAllowances = totalAllowances * prorationInfo.prorationFactor;
    }

    // Calculate gross salary
    const grossSalary = baseSalary + totalAllowances;

    // Calculate statutory deductions (automatically applied for compliance)
    let totalDeductions = 0;
    const statutoryDeductions: { name: string; amount: number; type: string }[] = [];

    // 1. Income Tax (statutory)
    for (const taxRule of approvedTaxRules) {
      const taxAmount = (grossSalary * taxRule.rate) / 100;
      totalDeductions += taxAmount;
      statutoryDeductions.push({
        name: taxRule.name || 'Income Tax',
        amount: taxAmount,
        type: 'Income Tax',
      });
    }

    // 2. Pension / Insurance Contributions (statutory) based on insurance brackets
    //    Deduction is computed on BASE SALARY and only for the bracket that matches the base salary range.
    for (const insurance of approvedInsuranceBrackets) {
      if (baseSalary >= insurance.minSalary && baseSalary <= insurance.maxSalary) {
        const insuranceName = insurance.name.toLowerCase();
        const isPension = insuranceName.includes('pension') || insuranceName.includes('retirement');
        
        const employeeContribution = (baseSalary * insurance.employeeRate) / 100;
        totalDeductions += employeeContribution;
        statutoryDeductions.push({
          name: insurance.name,
          amount: employeeContribution,
          type: isPension ? 'Pension' : 'Insurance',
        });
      }
    }

    // 3. Social Insurance / Health Insurance (statutory)
    // Already handled above in insurance brackets, but we ensure all are applied

    // 4. Labor Law Deductions (statutory) - from approved policies with DEDUCTION type
    for (const policy of approvedPolicies) {
      if (this.isStatutoryPolicyApplicable(policy, employee, payrollPeriodEnd)) {
        const rule = policy.ruleDefinition;
        if (rule && grossSalary >= rule.thresholdAmount) {
          const policyAmount = (grossSalary * rule.percentage) / 100 + rule.fixedAmount;
          totalDeductions += policyAmount;
          statutoryDeductions.push({
            name: policy.policyName,
            amount: policyAmount,
            type: 'Labor Law Deduction',
          });
        }
      }
    }

    // Calculate net pay
    const netSalary = grossSalary - totalDeductions;
    const netPay = Math.max(0, netSalary);

    // Flag negative net pay
    if (netSalary < 0) {
      irregularities.push(`Negative net pay: ${netSalary.toFixed(2)}`);
    }

    // Check for missing bank account
    // TODO: Add actual bank account validation when bank details schema is available
    // For now, we'll default to VALID but flag if validation is needed
    let bankStatus = BankStatus.VALID;
    
    // If net pay is positive, bank account should be validated
    // This check should be enhanced when bank details are integrated
    // For now, we'll assume bank details exist (VALID) but this can be changed
    // based on actual bank account validation logic

    const employeePayrollDetail = new this.employeePayrollDetailsModel({
      employeeId,
      payrollRunId,
      baseSalary,
      allowances: totalAllowances,
      deductions: totalDeductions,
      netSalary,
      netPay,
      bankStatus,
      exceptions: irregularities.length > 0 ? irregularities.join('; ') : undefined,
    });

    return {
      employeePayrollDetail,
      netPay,
      exceptions: irregularities.length > 0 ? irregularities.join('; ') : undefined,
    };
  }

  private calculateProration(
    dateOfHire: Date,
    contractEndDate: Date | undefined,
    employeeStatus: string,
    statusEffectiveFrom: Date | undefined,
    payrollPeriodStart: Date,
    payrollPeriodEnd: Date,
  ): {
    isProrated: boolean;
    prorationFactor: number;
    daysWorked: number;
    totalDays: number;
    reason: string;
  } {
    // Calculate total days in the payroll period (month)
    const totalDays = new Date(payrollPeriodEnd.getFullYear(), payrollPeriodEnd.getMonth() + 1, 0).getDate();

    const periodStart = new Date(payrollPeriodStart);
    // normalize to date-only (local) to avoid timezone/time-of-day off-by-one issues
    const toDateOnly = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate());
    const periodStartDateOnly = toDateOnly(periodStart);
    let effectiveStartDate = toDateOnly(periodStart);
    let effectiveEndDate = toDateOnly(payrollPeriodEnd);

    // Safely parse hire date if provided
    if (dateOfHire) {
      const hireDateRaw = new Date(dateOfHire);
      if (!isNaN(hireDateRaw.getTime())) {
        const hireDate = toDateOnly(hireDateRaw);
        // Only treat as mid-month if hireDate is strictly after the period start date
        if (hireDate.getTime() > periodStartDateOnly.getTime()) effectiveStartDate = hireDate;
      }
    }

    // Check for termination (using statusEffectiveFrom as termination date)
    if (employeeStatus === 'TERMINATED' && statusEffectiveFrom) {
      const terminationDateRaw = new Date(statusEffectiveFrom);
      if (!isNaN(terminationDateRaw.getTime())) {
        const terminationDate = toDateOnly(terminationDateRaw);
        if (terminationDate.getTime() >= periodStartDateOnly.getTime() && terminationDate.getTime() <= effectiveEndDate.getTime()) {
          effectiveEndDate = terminationDate;
        }
      }
    }

    // Check for contract end date
    if (contractEndDate) {
      const contractEndRaw = new Date(contractEndDate);
      if (!isNaN(contractEndRaw.getTime())) {
        const contractEnd = toDateOnly(contractEndRaw);
        if (contractEnd.getTime() >= periodStartDateOnly.getTime() && contractEnd.getTime() <= effectiveEndDate.getTime()) {
          effectiveEndDate = contractEnd;
        }
      }
    }

    // If effective start is after effective end, employee did not work in this period
    if (effectiveStartDate > effectiveEndDate) {
      return {
        isProrated: true,
        prorationFactor: 0,
        daysWorked: 0,
        totalDays,
        reason: 'No work during period',
      };
    }

    // Calculate days worked (inclusive) using date-only values
    const msPerDay = 1000 * 60 * 60 * 24;
    const timeDiff = effectiveEndDate.getTime() - effectiveStartDate.getTime();
    const daysWorked = Math.max(1, Math.floor(timeDiff / msPerDay) + 1);

    const prorationFactor = Math.min(1, daysWorked / totalDays);
    const isProrated = prorationFactor < 1;

    // Determine reason for proration
    let reason = '';
    if (dateOfHire && new Date(dateOfHire) > periodStart) {
      reason = `Mid-month hire`;
    }
    if (
      (employeeStatus === 'TERMINATED' && statusEffectiveFrom && new Date(statusEffectiveFrom) < payrollPeriodEnd) ||
      (contractEndDate && new Date(contractEndDate) < payrollPeriodEnd)
    ) {
      reason = reason ? `${reason}, Mid-month termination` : 'Mid-month termination';
    }

    return {
      isProrated,
      prorationFactor,
      daysWorked,
      totalDays,
      reason: reason || 'Full period',
    };
  }

  private isStatutoryPolicyApplicable(
    policy: payrollPolicies,
    employee: any,
    payrollPeriodEnd: Date,
  ): boolean {
    // Check if policy is effective
    if (policy.effectiveDate > payrollPeriodEnd) {
      return false;
    }

    // Check applicability based on employee type
    switch (policy.applicability) {
      case Applicability.AllEmployees:
        return true;
      case Applicability.FULL_TIME:
        return employee.workType === WorkType.FULL_TIME;
      case Applicability.PART_TIME:
        return employee.workType === WorkType.PART_TIME;
      case Applicability.CONTRACTORS:
        return employee.contractType !== undefined;
      default:
        return false;
    }
  }

  async generatePayslips(payrollRunId: string): Promise<{ generated: number; errors: number }> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    // Allow generation for APPROVED or LOCKED runs. Previously only APPROVED
    // runs were allowed which prevented specialists from generating payslips
    // for runs that had been locked after approvals.
    if (
      payrollRun.status !== PayRollStatus.APPROVED &&
      payrollRun.status !== PayRollStatus.LOCKED
    ) {
      throw new BadRequestException(
        `Payslips can only be generated for APPROVED or LOCKED payroll runs. Current status: ${payrollRun.status}`,
      );
    }

    // If payroll is explicitly marked as locked we still allow generation; keep
    // validation to prevent accidental generation for other statuses.

    // Get all employee payroll details for this run (lean to work with plain objects)
    const employeeDetails = await this.employeePayrollDetailsModel
      .find({ payrollRunId: payrollRun._id })
      .populate('employeeId')
      .lean()
      .exec();

    let generated = 0;
    let errors = 0;
    const errorsDetails: string[] = [];

    // Iterate and create payslips safely
    for (const detail of employeeDetails) {
      try {
        const employeeId = (detail.employeeId && (detail.employeeId as any)._id) ? (detail.employeeId as any)._id : detail.employeeId;

        // Defensive: ensure we have an employeeId and payrollRunId
        if (!employeeId || !payrollRun._id) {
          errors++;
          errorsDetails.push('Missing employeeId or payrollRunId for payroll detail: ' + JSON.stringify(detail._id));
          continue;
        }

        // Skip if payslip already exists
        const existingPayslip = await this.paySlipModel.findOne({ employeeId, payrollRunId: payrollRun._id }).lean().exec();
        if (existingPayslip) continue;

        // Build a minimal, valid payslip payload compatible with schema
        const totalGross = Number((detail.baseSalary || 0) + (detail.allowances || 0) + (detail.bonus || 0) + (detail.benefit || 0));
        const totalDeductions = Number(detail.deductions || 0);
        const netPay = Number(detail.netPay || 0);

        const payslipPayload: any = {
          employeeId: employeeId,
          payrollRunId: payrollRun._id,
          totalGrossSalary: totalGross,
          totaDeductions: totalDeductions,
          netPay: netPay,
          paymentStatus: PaySlipPaymentStatus.PENDING,
        };

        // Attach earningsDetails only if we have useful breakdown
        const earningsDetails: any = {};
        if (typeof detail.baseSalary === 'number') earningsDetails.baseSalary = Number(detail.baseSalary);
        // `earningsDetails.allowances` in the payslip schema is an embedded array.
        // Only attach it when we have a breakdown array; otherwise keep the numeric
        // allowance value on the parent payslip totals to avoid casting errors.
        if (Array.isArray((detail as any).earningsBreakdown) && (detail as any).earningsBreakdown.length > 0) {
          earningsDetails.allowances = (detail as any).earningsBreakdown;
        }
        // Bonuses and benefits are embedded arrays in the schema; only include
        // them when a breakdown is available as arrays.
        if (Array.isArray((detail as any).bonusesBreakdown) && (detail as any).bonusesBreakdown.length > 0) {
          earningsDetails.bonuses = (detail as any).bonusesBreakdown;
        }
        if (Array.isArray((detail as any).benefitsBreakdown) && (detail as any).benefitsBreakdown.length > 0) {
          earningsDetails.benefits = (detail as any).benefitsBreakdown;
        }
        if (Object.keys(earningsDetails).length > 0) payslipPayload.earningsDetails = earningsDetails;

        // Attach deductionsDetails only if available
        const deductionsDetails: any = {};
        if (typeof detail.deductions === 'number' && detail.deductions > 0) deductionsDetails.totalDeductions = Number(detail.deductions);
        if (Object.keys(deductionsDetails).length > 0) payslipPayload.deductionsDetails = deductionsDetails;

        // Create and save payslip
        await this.paySlipModel.create(payslipPayload);
        generated++;
      } catch (err: any) {
        errors++;
        const message = err?.message || String(err);
        console.error('Error generating payslip for detail:', detail?._id, message);
        errorsDetails.push(message);
      }
    }
    // Mark all generated payslips as PAID
        await this.paySlipModel.updateMany(
       { 
        payrollRunId: payrollRun._id, paymentStatus: PaySlipPaymentStatus.PENDING
       },
       {
         $set: { paymentStatus: PaySlipPaymentStatus.PAID 
       } 
      },
);

          // Mark the payroll run as fully paid
      payrollRun.paymentStatus = PayRollPaymentStatus.PAID;
      await payrollRun.save();

    // Return basic stats and sample errors to aid debugging
    return { generated, errors, errorsDetails: errorsDetails.slice(0, 20) } as any;
  }

  async generatePayslipPDF(payslipId: string): Promise<Buffer> {
    if (!Types.ObjectId.isValid(payslipId)) {
      throw new BadRequestException('Invalid payslip ID');
    }

    const payslip = await this.paySlipModel
      .findById(payslipId)
      .populate('employeeId')
      .populate('payrollRunId')
      .exec();

    if (!payslip) {
      throw new NotFoundException('Payslip not found');
    }

    const employee = payslip.employeeId as any;
    const payrollRun = payslip.payrollRunId as any;

    // Create PDF document
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];

    // Collect PDF data
    doc.on('data', (chunk) => chunks.push(chunk));
    
    return new Promise((resolve, reject) => {
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(chunks);
        resolve(pdfBuffer);
      });

      doc.on('error', reject);

      // Header
      doc.fontSize(20).text('PAYSLIP', { align: 'center' });
      doc.moveDown();

      // Company/Entity Info
      doc.fontSize(14).text(payrollRun?.entity || 'Company Name', { align: 'center' });
      doc.moveDown(0.5);

      // Payroll Period
      const payrollPeriod = payrollRun?.payrollPeriod
        ? new Date(payrollRun.payrollPeriod).toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
          })
        : 'N/A';
      doc.fontSize(12).text(`Pay Period: ${payrollPeriod}`, { align: 'center' });
      doc.moveDown();

      // Employee Information
      doc.fontSize(14).text('Employee Information', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11);
      doc.text(`Employee Number: ${employee?.employeeNumber || 'N/A'}`);
      doc.text(`Name: ${employee?.firstName || ''} ${employee?.lastName || ''}`.trim() || 'N/A');
      if (employee?.workEmail) {
        doc.text(`Email: ${employee.workEmail}`);
      }
      doc.moveDown();



      // Earnings Section
      doc.fontSize(14).text('Earnings', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11);
      
      const earnings = payslip.earningsDetails || {};
      doc.text(`Base Salary: $${(earnings.baseSalary || 0).toFixed(2)}`, { continued: true, align: 'left' });
      
      if (earnings.allowances && Array.isArray(earnings.allowances)) {
        earnings.allowances.forEach((allowance: any) => {
          doc.text(`${allowance.name || 'Allowance'}: $${(allowance.amount || 0).toFixed(2)}`);
        });
      }
      
      if (earnings.bonuses && Array.isArray(earnings.bonuses)) {
        earnings.bonuses.forEach((bonus: any) => {
          doc.text(`Bonus: $${(bonus.amount || 0).toFixed(2)}`);
        });
      }
      
      if (earnings.benefits && Array.isArray(earnings.benefits)) {
        earnings.benefits.forEach((benefit: any) => {
          doc.text(`Benefit: $${(benefit.amount || 0).toFixed(2)}`);
        });
      }

      doc.moveDown();
      doc.fontSize(12).text(`Total Gross Salary: $${payslip.totalGrossSalary.toFixed(2)}`, { align: 'right' });
      doc.moveDown();

      // Deductions Section
      doc.fontSize(14).text('Deductions', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11);
      
      const deductions = payslip.deductionsDetails || {};
      const earningsForDeductions = payslip.earningsDetails || {};
      const baseSalaryForDeductions =
        (earningsForDeductions && typeof (earningsForDeductions as any).baseSalary === 'number'
          ? (earningsForDeductions as any).baseSalary
          : payslip.totalGrossSalary) || 0;

      if (deductions.taxes && Array.isArray(deductions.taxes)) {
        deductions.taxes.forEach((tax: any) => {
          const taxAmount = (payslip.totalGrossSalary * (tax.rate || 0)) / 100;
          doc.text(`${tax.name || 'Tax'}: $${taxAmount.toFixed(2)}`);
        });
      }
      
      if (deductions.insurances && Array.isArray(deductions.insurances)) {
        deductions.insurances.forEach((insurance: any) => {
          const insuranceAmount = (baseSalaryForDeductions * (insurance.employeeRate || 0)) / 100;
          doc.text(`${insurance.name || 'Insurance'}: $${insuranceAmount.toFixed(2)}`);
        });
      }

      doc.moveDown();
      doc.fontSize(12).text(`Total Deductions: $${(payslip.totaDeductions || 0).toFixed(2)}`, { align: 'right' });
      doc.moveDown(2);

      // Net Pay
      doc.fontSize(16).text(`NET PAY: $${payslip.netPay.toFixed(2)}`, { align: 'center', underline: true });
      doc.moveDown(2);

      // Footer
      doc.fontSize(10).text('This is a computer-generated payslip.', { align: 'center' });
      doc.text(`Generated on: ${new Date().toLocaleDateString('en-US')}`, { align: 'center' });
      doc.text(`Payslip ID: ${payslipId}`, { align: 'center' });

      // Finalize PDF
      doc.end();
    });
  }

  /**
   * Return payslips for a given payroll run. Accepts either a Mongo ObjectId
   * or a human-friendly runId (e.g., PR-2025-12-0001).
   */
  async getPayslipsForRun(payrollRunId: string): Promise<any[]> {
    let payrollRunObjectId: Types.ObjectId | null = null;

    if (Types.ObjectId.isValid(payrollRunId)) {
      payrollRunObjectId = new Types.ObjectId(payrollRunId);
    } else {
      const run = await this.payrollRunsModel.findOne({ runId: payrollRunId }).exec();
      if (!run) {
        throw new BadRequestException('Invalid payroll run ID');
      }
      payrollRunObjectId = run._id as Types.ObjectId;
    }

    return this.paySlipModel
      .find({ payrollRunId: payrollRunObjectId })
      .populate('employeeId')
      .populate('payrollRunId')
      .sort({ createdAt: -1 })
      .exec();
  }

  /**
   * Escalate an irregularity to Payroll Manager for review
   * Payroll Specialists can escalate irregularities they cannot resolve
   * Uses existing exceptions field to track escalation status
   */
  async escalateIrregularity(
    employeePayrollDetailId: string,
    irregularityDescription: string,
    escalationNotes: string | undefined,
    payrollSpecialistId: string,
  ): Promise<employeePayrollDetails> {
    if (!Types.ObjectId.isValid(employeePayrollDetailId)) {
      throw new BadRequestException('Invalid employee payroll detail ID');
    }

    if (!Types.ObjectId.isValid(payrollSpecialistId)) {
      throw new BadRequestException('Invalid payroll specialist ID');
    }

    // Get the employee payroll detail
    const employeePayrollDetail = await this.employeePayrollDetailsModel
      .findById(employeePayrollDetailId)
      .populate('employeeId')
      .populate('payrollRunId')
      .exec();

    if (!employeePayrollDetail) {
      throw new NotFoundException('Employee payroll detail not found');
    }

    // Check if already escalated (check if exceptions contains ESCALATED marker)
    if (employeePayrollDetail.exceptions && employeePayrollDetail.exceptions.includes('[ESCALATED]')) {
      throw new BadRequestException(
        'This irregularity has already been escalated and is pending resolution.',
      );
    }

    // Append escalation information to exceptions field
    const escalationMarker = `[ESCALATED] ${irregularityDescription}`;
    const escalationInfo = escalationNotes 
      ? ` | Escalation Notes: ${escalationNotes} | Escalated By: ${payrollSpecialistId}`
      : ` | Escalated By: ${payrollSpecialistId}`;
    
    const updatedExceptions = employeePayrollDetail.exceptions
      ? `${employeePayrollDetail.exceptions}; ${escalationMarker}${escalationInfo}`
      : `${escalationMarker}${escalationInfo}`;

    employeePayrollDetail.exceptions = updatedExceptions;

    return employeePayrollDetail.save();
  }

  /**
   * Get all escalated irregularities for Payroll Manager review
   * Finds employeePayrollDetails where exceptions field contains [ESCALATED] marker
   */
  async getEscalatedIrregularities(): Promise<employeePayrollDetails[]> {
    return this.employeePayrollDetailsModel
      .find({
        exceptions: { $regex: /\[ESCALATED\]/, $options: 'i' },
      })
      .populate('employeeId')
      .populate('payrollRunId')
      .sort({ createdAt: -1 })
      .exec();
  }

  /**
   * Get escalated irregularities for a specific payroll run
   */
  async getEscalatedIrregularitiesByPayrollRun(payrollRunId: string): Promise<employeePayrollDetails[]> {
    // Accept either a Mongo ObjectId or a human-friendly runId (e.g., PR-2025-12-0001).
    let payrollRunObjectId: Types.ObjectId | null = null;

    if (Types.ObjectId.isValid(payrollRunId)) {
      payrollRunObjectId = new Types.ObjectId(payrollRunId);
    } else {
      // Try to resolve by runId field on payrollRuns collection
      const run = await this.payrollRunsModel.findOne({ runId: payrollRunId }).exec();
      if (!run) {
        throw new BadRequestException('Invalid payroll run ID');
      }
      payrollRunObjectId = run._id as Types.ObjectId;
    }

    return this.employeePayrollDetailsModel
      .find({
        payrollRunId: payrollRunObjectId,
        exceptions: { $regex: /\[ESCALATED\]/, $options: 'i' },
      })
      .populate('employeeId')
      .populate('payrollRunId')
      .sort({ createdAt: -1 })
      .exec();
  }

  /**
   * Resolve an escalated irregularity
   * Payroll Managers can resolve or dismiss escalated irregularities
   */
  async resolveIrregularity(
    employeePayrollDetailId: string,
    managerId: string,
    resolutionNotes: string,
    status: string,
  ): Promise<employeePayrollDetails> {
    if (!Types.ObjectId.isValid(employeePayrollDetailId)) {
      throw new BadRequestException('Invalid employee payroll detail ID');
    }

    if (!Types.ObjectId.isValid(managerId)) {
      throw new BadRequestException('Invalid manager ID');
    }

    if (status !== 'resolved' && status !== 'dismissed') {
      throw new BadRequestException(
        `Invalid status. Only 'resolved' or 'dismissed' statuses are allowed for resolution.`,
      );
    }

    // Validate resolution notes length
    if (!resolutionNotes || resolutionNotes.trim().length < 10) {
      throw new BadRequestException(
        'Resolution notes must be at least 10 characters to document the decision.',
      );
    }

    const employeePayrollDetail = await this.employeePayrollDetailsModel
      .findById(employeePayrollDetailId)
      .exec();

    if (!employeePayrollDetail) {
      throw new NotFoundException('Employee payroll detail not found');
    }

    // Check if it's escalated
    if (!employeePayrollDetail.exceptions || !employeePayrollDetail.exceptions.includes('[ESCALATED]')) {
      throw new BadRequestException(
        'This irregularity has not been escalated or has already been resolved.',
      );
    }

    // Check if already resolved
    if (employeePayrollDetail.exceptions.includes('[RESOLVED]') || employeePayrollDetail.exceptions.includes('[DISMISSED]')) {
      throw new BadRequestException(
        'This irregularity has already been resolved or dismissed.',
      );
    }

    // Append resolution information to exceptions field
    const resolutionMarker = status === 'resolved' ? '[RESOLVED]' : '[DISMISSED]';
    const resolutionInfo = ` | Resolution: ${resolutionNotes} | Resolved By: ${managerId} | Resolved At: ${new Date().toISOString()}`;
    // Keep the '[ESCALATED]' marker so the record remains visible in the escalated list,
    // but append the resolution marker so the UI can indicate it was resolved/dismissed.
    const updatedExceptions = employeePayrollDetail.exceptions
      ? `${employeePayrollDetail.exceptions}; ${resolutionMarker}${resolutionInfo}`
      : `${resolutionMarker}${resolutionInfo}`;

    employeePayrollDetail.exceptions = updatedExceptions;

    return employeePayrollDetail.save();
  }
}
//. alo 3ayz a3ml pushh
@Injectable()
export class EmployeeSigningBonusService {
  constructor(
    @InjectModel(employeeSigningBonus.name)
    private readonly signingBonusModel: Model<employeeSigningBonus>,
  ) { }

  /**
   * Create a new signing bonus record
   * Used by HR/Payroll to manually add signing bonuses
   */
  async createSigningBonus(dto: any, creatorId: string) {
    // Validate employee exists
    const employeeExists = await this.signingBonusModel.db.collection('employee_profiles').findOne({
      _id: new Types.ObjectId(dto.employeeId)
    });

    if (!employeeExists) {
      throw new NotFoundException(`Employee with ID ${dto.employeeId} not found`);
    }

    // Find or create a default signing bonus configuration for manual entries
    let signingBonusConfigId = dto.signingBonusId;

    if (!signingBonusConfigId) {
      let defaultConfig = await this.signingBonusModel.db.collection('signingbonuses').findOne({
        positionName: 'Manual Entry'
      });

      if (!defaultConfig) {
        const newConfig = await this.signingBonusModel.db.collection('signingbonuses').insertOne({
          positionName: 'Manual Entry',
          amount: dto.givenAmount || 0,
          status: 'approved',
          createdBy: new Types.ObjectId(creatorId),
          createdAt: new Date(),
          updatedAt: new Date()
        });
        signingBonusConfigId = newConfig.insertedId;
      } else {
        signingBonusConfigId = defaultConfig._id;
      }
    }

    // Create new signing bonus with type field
    const newBonus = new this.signingBonusModel({
      employeeId: new Types.ObjectId(dto.employeeId),
      signingBonusId: new Types.ObjectId(signingBonusConfigId),
      givenAmount: dto.givenAmount,
      paymentDate: dto.paymentDate,
      status: 'pending',
      type: dto.type || 'Signing Bonus', // Save the compensation type
    });

    const savedBonus = await newBonus.save();

    return {
      message: 'Compensation created successfully',
      bonus: savedBonus,
    };
  }

  /**
   * Auto-process signing bonuses for a payroll run
   * Fetches all pending bonuses for new hires and marks them for processing
   */
  async autoProcessSigningBonuses(runId: string) {
    const pendingBonuses = await this.signingBonusModel.find({
      status: 'pending',
      payrollRunId: runId,
    });

    if (pendingBonuses.length === 0) {
      return {
        message: 'No pending signing bonuses found for this payroll run',
        count: 0,
      };
    }

    // Mark bonuses as auto-processed
    await this.signingBonusModel.updateMany(
      { status: 'pending', payrollRunId: runId },
      {
        status: 'auto_processed',
        processedAt: new Date(),
      }
    );

    return {
      message: `Successfully auto-processed ${pendingBonuses.length} signing bonuses`,
      count: pendingBonuses.length,
      bonuses: pendingBonuses,
    };
  }

  /**
   * Manual edit of signing bonus
   * Allows payroll specialist to modify bonus details before approval
   */
  async editSigningBonus(dto: EditSigningBonusDto, editorId: string) {
    const bonus = await this.signingBonusModel.findById(dto.bonusId);

    if (!bonus) {
      throw new NotFoundException(`Signing bonus with ID ${dto.bonusId} not found`);
    }

    if (bonus.status === 'approved' || bonus.status === 'rejected') {
      throw new BadRequestException(
        `Cannot edit bonus with status: ${bonus.status}`
      );
    }

    const updateData: any = {
      lastEditedBy: editorId,
      lastEditedAt: new Date(),
    };

    if (dto.adjustedAmount !== undefined) {
      updateData.givenAmount = dto.adjustedAmount;
      updateData.originalAmount = (bonus as any).givenAmount; // Store original
    }

    if (dto.editReason) {
      updateData.editReason = dto.editReason;
    }

    if (dto.notes) {
      updateData.notes = dto.notes;
    }

    if (dto.currency) {
      updateData.currency = dto.currency;
    }

    if (dto.paymentDate) {
      updateData.paymentDate = dto.paymentDate;
    }

    const updatedBonus = await this.signingBonusModel.findByIdAndUpdate(
      dto.bonusId,
      updateData,
      { new: true }
    );

    return {
      message: 'Signing bonus updated successfully',
      bonus: updatedBonus,
    };
  }

  /**
   * Review signing bonus details
   * Retrieves bonus information for review before approval/rejection
   */
  async reviewSigningBonus(bonusId: string, reviewerId: string) {
    const bonus = await this.signingBonusModel
      .findById(bonusId)
      .populate('employeeId', 'firstName lastName email')
      .populate('signingBonusId', 'bonusName amount description');

    if (!bonus) {
      throw new NotFoundException(`Signing bonus with ID ${bonusId} not found`);
    }

    return {
      message: 'Signing bonus retrieved for review',
      bonus,
    };
  }

  /**
   * Approve signing bonus
   * Marks bonus as approved and ready for payroll processing
   */
  async approveSigningBonus(dto: ApproveSigningBonusDto, approverId: string) {
    const bonus = await this.signingBonusModel.findById(dto.bonusId);

    if (!bonus) {
      throw new NotFoundException(`Signing bonus with ID ${dto.bonusId} not found`);
    }

    if (bonus.status === 'approved') {
      throw new BadRequestException('Signing bonus is already approved');
    }

    if (bonus.status === 'rejected') {
      throw new BadRequestException('Cannot approve a rejected bonus');
    }

    const updateData: any = {
      status: 'approved',
      approvedBy: approverId,
      approvedAt: new Date(),
      approverComments: dto.approverComments,
    };

    // If approver adjusted the amount during approval
    if (dto.adjustedAmount !== undefined && dto.adjustedAmount !== (bonus as any).givenAmount) {
      updateData.givenAmount = dto.adjustedAmount;
      updateData.originalAmount = (bonus as any).givenAmount;
    }

    const approvedBonus = await this.signingBonusModel.findByIdAndUpdate(
      dto.bonusId,
      updateData,
      { new: true }
    );

    return {
      message: 'Signing bonus approved successfully',
      bonus: approvedBonus,
    };
  }

  /**
   * Reject signing bonus
   * Marks bonus as rejected with reason, excludes from payroll processing
   */
  async rejectSigningBonus(dto: RejectSigningBonusDto, approverId: string) {
    console.log('=== REJECT SIGNING BONUS DEBUG ===');
    console.log('Collection name:', this.signingBonusModel.collection.name);
    console.log('Searching for bonus ID:', dto.bonusId);
    console.log('All documents:', await this.signingBonusModel.find().limit(5).lean());

    const bonus = await this.signingBonusModel.findById(dto.bonusId);
    console.log('Found bonus:', bonus);

    if (!bonus) {
      throw new NotFoundException(`Signing bonus with ID ${dto.bonusId} not found`);
    }

    if (bonus.status === 'approved') {
      throw new BadRequestException('Cannot reject an already approved bonus');
    }

    if (bonus.status === 'rejected') {
      throw new BadRequestException('Signing bonus is already rejected');
    }

    const rejectedBonus = await this.signingBonusModel.findByIdAndUpdate(
      dto.bonusId,
      {
        status: 'rejected',
        rejectedBy: approverId,
        rejectedAt: new Date(),
        rejectionReason: dto.rejectionReason,
      },
      { new: true }
    );

    return {
      message: 'Signing bonus rejected successfully',
      bonus: rejectedBonus,
    };
  }

  /**
   * Get all signing bonuses for a payroll run
   */
  async getSigningBonusesByRun(runId: string) {
    const bonuses = await this.signingBonusModel
      .find({ payrollRunId: runId })
      .populate('employeeId', 'name email position');

    return {
      count: bonuses.length,
      bonuses,
    };
  }

  /**
   * Get all signing bonuses (including approved/rejected)
   */
  async getPendingSigningBonuses() {
    const allBonuses = await this.signingBonusModel
      .find({}) // Fetch ALL bonuses, not just pending
      .populate('employeeId', 'name email position firstName lastName')
      .sort({ createdAt: -1 });

    return {
      count: allBonuses.length,
      bonuses: allBonuses,
    };
  }
}

@Injectable()
export class EmployeeTerminationResignationService {
  constructor(
    @InjectModel(EmployeeTerminationResignation.name)
    private readonly terminationResignationModel: Model<EmployeeTerminationResignation>,
  ) { }

  /**
   * Create a new termination/resignation benefit
   * Used by HR/Payroll to manually add benefits
   */
  async createBenefit(dto: any, creatorId: string) {
    // Validate employee exists
    const employee = await this.terminationResignationModel.db.collection('employee_profiles').findOne({
      _id: new Types.ObjectId(dto.employeeId)
    });

    if (!employee) {
      throw new NotFoundException(`Employee with ID ${dto.employeeId} not found`);
    }

    // 1. Find or create a default benefit configuration (terminationAndResignationBenefits)
    let benefitConfigId = dto.benefitId;

    if (!benefitConfigId) {
      // Try to find a "Manual Entry" config
      let defaultConfig = await this.terminationResignationModel.db.collection('terminationandresignationbenefits').findOne({
        name: 'Manual Entry'
      });

      if (!defaultConfig) {
        // Create one if it doesn't exist
        const newConfig = await this.terminationResignationModel.db.collection('terminationandresignationbenefits').insertOne({
          name: 'Manual Entry',
          description: 'Auto-generated for manual entries',
          type: dto.type === 'Resignation' ? 'Resignation' : 'Termination',
          calculationMethod: 'Fixed Amount',
          amount: dto.givenAmount || 0,
          isActive: true,
          createdAt: new Date(),
          updatedAt: new Date()
        });
        benefitConfigId = newConfig.insertedId;
      } else {
        benefitConfigId = defaultConfig._id;
      }
    }

    // 2. Find or create a TerminationRequest
    const contract = await this.terminationResignationModel.db.collection('contracts').findOne({
      employeeId: new Types.ObjectId(dto.employeeId)
    });

    let terminationId;

    // Check for existing request
    const existingTermination = await this.terminationResignationModel.db.collection('terminationrequests').findOne({
      employeeId: new Types.ObjectId(dto.employeeId)
    });

    if (existingTermination) {
      // Use existing request
      terminationId = existingTermination._id;

      // Validate prerequisites if not overridden
      if (!dto.overridePrerequisites) {
        if (!['approved', 'completed'].includes(existingTermination.status.toLowerCase())) {
          throw new BadRequestException('Termination/Resignation request is not yet approved or completed');
        }

        // Check Clearance Checklist
        const clearance = await this.terminationResignationModel.db.collection('clearancechecklists').findOne({
          employeeId: new Types.ObjectId(dto.employeeId)
        });

        if (!clearance) {
          throw new BadRequestException('No clearance checklist found for this employee');
        }

        if (!clearance.allSignoffsCompleted || !clearance.allAssetsReturned) {
          throw new BadRequestException('Employee clearance checklist is not fully completed (Sign-offs or Assets)');
        }
      }
    } else {
      // No existing request - Create a new one for Manual Entry
      // We implicitly skip prerequisites checks here as we are auto-generating the approved request
      const newTerminationRequest = await this.terminationResignationModel.db.collection('terminationrequests').insertOne({
        employeeId: new Types.ObjectId(dto.employeeId),
        contractId: contract ? contract._id : new Types.ObjectId(),
        initiator: 'HR',
        reason: 'Manual Payroll Entry',
        status: 'Approved',
        terminationDate: new Date(dto.paymentDate || Date.now()),
        createdAt: new Date(),
        updatedAt: new Date()
      });
      terminationId = newTerminationRequest.insertedId;
    }

    // 3. Create the EmployeeTerminationResignation record
    // We use collection.insertOne to bypass strict schema validation and save payrollRunId
    const benefitDoc = {
      employeeId: new Types.ObjectId(dto.employeeId),
      benefitId: new Types.ObjectId(benefitConfigId),
      terminationId: new Types.ObjectId(terminationId),
      givenAmount: dto.givenAmount,
      status: 'pending',
      payrollRunId: dto.payrollRunId ? new Types.ObjectId(dto.payrollRunId) : undefined, // Save payrollRunId if provided
      createdAt: new Date(),
      updatedAt: new Date(),
      __v: 0
    };

    const result = await this.terminationResignationModel.collection.insertOne(benefitDoc);

    // Return the created document (casted to model for consistency)
    return {
      message: 'Benefit created successfully',
      benefit: { ...benefitDoc, _id: result.insertedId },
    };
  }


  /**
   * Auto-process termination benefits for a payroll run
   * Fetches all terminated employees and calculates benefits according to business rules
   */
  async autoProcessTerminationBenefits(runId: string) {
    const pendingBenefits = await this.terminationResignationModel.find({
      status: 'pending',
      payrollRunId: runId,
    });

    if (pendingBenefits.length === 0) {
      return {
        message: 'No pending termination/resignation benefits found for this payroll run',
        count: 0,
      };
    }

    // Mark benefits as auto-processed
    await this.terminationResignationModel.updateMany(
      { status: 'pending', payrollRunId: runId },
      {
        status: 'auto_processed',
        processedAt: new Date(),
      }
    );

    return {
      message: `Successfully auto-processed ${pendingBenefits.length} termination/resignation benefits`,
      count: pendingBenefits.length,
      benefits: pendingBenefits,
    };
  }

  /**
   * Auto-process resignation benefits for a payroll run
   * Fetches all resigned employees and calculates benefits according to business rules
   */
  async autoProcessResignationBenefits(runId: string) {
    const pendingBenefits = await this.terminationResignationModel.find({
      status: 'pending',
      payrollRunId: runId,
    });

    if (pendingBenefits.length === 0) {
      return {
        message: 'No pending benefits found for this payroll run',
        count: 0,
      };
    }

    // Mark benefits as auto-processed
    await this.terminationResignationModel.updateMany(
      { status: 'pending', payrollRunId: runId },
      {
        status: 'auto_processed',
        processedAt: new Date(),
      }
    );

    return {
      message: `Successfully auto-processed ${pendingBenefits.length} benefits`,
      count: pendingBenefits.length,
      benefits: pendingBenefits,
    };
  }

  /**
   * Manual edit of termination/resignation benefit
   * Allows payroll specialist to modify benefit details before approval
   */
  async editBenefit(dto: EmployeeTerminationResignationEditDto, editorId: string) {
    console.log(`[DEBUG] editBenefit called with ID: ${dto.benefitId}`);
    const benefit = await this.terminationResignationModel.findById(dto.benefitId);

    if (!benefit) {
      const all = await this.terminationResignationModel.find({}, '_id').exec();
      console.log(`[DEBUG] Benefit not found. Available IDs: ${all.map(d => d._id).join(', ')}`);
      throw new NotFoundException(`Benefit with ID ${dto.benefitId} not found`);
    }

    if (benefit.status === 'approved' || benefit.status === 'rejected') {
      throw new BadRequestException(
        `Cannot edit benefit with status: ${benefit.status}`
      );
    }

    const updateData: any = {
      lastEditedBy: editorId,
      lastEditedAt: new Date(),
    };

    if (dto.adjustedAmount !== undefined) {
      updateData.givenAmount = dto.adjustedAmount;
      updateData.originalAmount = benefit.get('givenAmount'); // Store original
    }

    if (dto.editReason) {
      updateData.editReason = dto.editReason;
    }

    if (dto.notes) {
      updateData.notes = dto.notes;
    }

    if (dto.currency) {
      updateData.currency = dto.currency;
    }

    if (dto.paymentDate) {
      updateData.paymentDate = dto.paymentDate; // Note: schema might not have paymentDate, but we can save it or map to createdAt/effectiveDate if needed. 
      // Actually, for termination/resignation, the schema might rely on createdAt or terminationDate. 
      // But let's save it as paymentDate if the schema allows or if it's flexible (using collection.insertOne earlier suggests flexibility, but findByIdAndUpdate validates against schema if strict).
      // Checking schema... it's not shown but let's assume we can add it or it's there. 
      // If schema is strict, this might be ignored. But let's try.
      // Wait, the create method used `terminationDate` on the `terminationrequests` collection, but `paymentDate` wasn't explicitly on `EmployeeTerminationResignation` doc in createBenefit except maybe implicitly?
      // In createBenefit: `terminationDate: new Date(dto.paymentDate || Date.now())` for termination request.
      // For the benefit doc: it didn't use paymentDate.
      // However, the frontend expects `effectiveDate` which maps to `createdAt` or `paymentDate`.
      // Let's add it to updateData. If schema ignores it, we might need to update schema too.
      // But for now, let's add it.
    }

    const updatedBenefit = await this.terminationResignationModel.findByIdAndUpdate(
      dto.benefitId,
      updateData,
      { new: true }
    );

    return {
      message: 'Benefit updated successfully',
      benefit: updatedBenefit,
    };
  }

  /**
   * Review termination/resignation benefit details
   * Retrieves benefit information for review before approval/rejection
   */
  async reviewBenefit(benefitId: string, reviewerId: string) {
    const benefit = await this.terminationResignationModel
      .findById(benefitId)
      .populate('employeeId', 'name email position department');

    if (!benefit) {
      throw new NotFoundException(`Benefit with ID ${benefitId} not found`);
    }

    // Log review activity
    await this.terminationResignationModel.findByIdAndUpdate(benefitId, {
      $push: {
        reviewHistory: {
          reviewerId,
          reviewedAt: new Date(),
          action: 'reviewed',
        },
      },
    });

    return {
      message: 'Benefit retrieved for review',
      benefit,
    };
  }

  /**
   * Approve termination/resignation benefit
   * Marks benefit as approved and ready for payroll processing
   */
  async approveBenefit(dto: EmployeeTerminationResignationApproveDto, approverId: string) {
    const benefit = await this.terminationResignationModel.findById(dto.benefitId);

    if (!benefit) {
      throw new NotFoundException(`Benefit with ID ${dto.benefitId} not found`);
    }

    if (benefit.status === 'approved') {
      throw new BadRequestException('Benefit is already approved');
    }

    if (benefit.status === 'rejected') {
      throw new BadRequestException('Cannot approve a rejected benefit');
    }

    const updateData: any = {
      status: 'approved',
      approvedBy: approverId,
      approvedAt: new Date(),
      approverComments: dto.approverComments,
    };

    // If approver adjusted the amount during approval
    if (dto.adjustedAmount !== undefined && dto.adjustedAmount !== benefit.get('givenAmount')) {
      updateData.givenAmount = dto.adjustedAmount;
      updateData.originalAmount = benefit.get('givenAmount');
    }

    const approvedBenefit = await this.terminationResignationModel.findByIdAndUpdate(
      dto.benefitId,
      updateData,
      { new: true }
    );

    return {
      message: 'Benefit approved successfully',
      benefit: approvedBenefit,
    };
  }

  /**
   * Reject termination/resignation benefit
   * Marks benefit as rejected with reason, excludes from payroll processing
   */
  async rejectBenefit(dto: EmployeeTerminationResignationRejectDto, approverId: string) {
    const benefit = await this.terminationResignationModel.findById(dto.benefitId);

    if (!benefit) {
      throw new NotFoundException(`Benefit with ID ${dto.benefitId} not found`);
    }

    if (benefit.status === 'approved') {
      throw new BadRequestException('Cannot reject an already approved benefit');
    }

    if (benefit.status === 'rejected') {
      throw new BadRequestException('Benefit is already rejected');
    }

    const rejectedBenefit = await this.terminationResignationModel.findByIdAndUpdate(
      dto.benefitId,
      {
        status: 'rejected',
        rejectedBy: approverId,
        rejectedAt: new Date(),
        rejectionReason: dto.rejectionReason,
      },
      { new: true }
    );

    return {
      message: 'Benefit rejected successfully',
      benefit: rejectedBenefit,
    };
  }

  /**
   * Get all termination benefits for a payroll run
   */
  async getTerminationBenefitsByRun(runId: string) {
    // Use lean() to get plain objects, allowing access to populated fields that might not be in schema
    const benefits = await this.terminationResignationModel
      .find({ payrollRunId: runId })
      .populate('employeeId', 'name email position department')
      .lean()
      .exec();

    if (benefits.length === 0) {
      return { count: 0, benefits: [] };
    }

    // Manually fetch benefit configs to ensure we get the 'type' field
    // which might be missing from the schema but present in DB
    const benefitConfigIds = benefits
      .map((b: any) => b.benefitId)
      .filter((id) => id); // Filter null/undefined

    const configs = await this.terminationResignationModel.db
      .collection('terminationandresignationbenefits')
      .find({ _id: { $in: benefitConfigIds } })
      .toArray();

    const configMap = new Map(configs.map((c: any) => [c._id.toString(), c]));

    // Filter by type 'Termination'
    const terminationBenefits = benefits.filter((b: any) => {
      if (!b.benefitId) return false;
      const config = configMap.get(b.benefitId.toString());
      if (!config) return false;

      // Check type if available
      if (config.type) {
        return config.type === 'Termination';
      }

      // Fallback: Check name for keywords
      const name = (config.name || '').toLowerCase();
      return name.includes('termination') || name.includes('end of service');
    });

    // Attach config to benefit object (simulating populate)
    const result = terminationBenefits.map((b: any) => ({
      ...b,
      benefitId: configMap.get(b.benefitId.toString())
    }));

    return {
      count: result.length,
      benefits: result,
    };
  }

  /**
   * Get all resignation benefits for a payroll run
   */
  async getResignationBenefitsByRun(runId: string) {
    // Use lean() to get plain objects
    const benefits = await this.terminationResignationModel
      .find({ payrollRunId: runId })
      .populate('employeeId', 'name email position department')
      .lean()
      .exec();

    if (benefits.length === 0) {
      return { count: 0, benefits: [] };
    }

    // Manually fetch benefit configs
    const benefitConfigIds = benefits
      .map((b: any) => b.benefitId)
      .filter((id) => id);

    const configs = await this.terminationResignationModel.db
      .collection('terminationandresignationbenefits')
      .find({ _id: { $in: benefitConfigIds } })
      .toArray();

    const configMap = new Map(configs.map((c: any) => [c._id.toString(), c]));

    // Filter by type 'Resignation'
    const resignationBenefits = benefits.filter((b: any) => {
      if (!b.benefitId) return false;
      const config = configMap.get(b.benefitId.toString());
      if (!config) return false;

      if (config.type) {
        return config.type === 'Resignation';
      }

      const name = (config.name || '').toLowerCase();
      return name.includes('resignation');
    });

    // Attach config to benefit object
    const result = resignationBenefits.map((b: any) => ({
      ...b,
      benefitId: configMap.get(b.benefitId.toString())
    }));

    return {
      count: result.length,
      benefits: result,
    };
  }

  /**
   * Get pending benefits requiring approval
   */
  async getPendingBenefits() {
    // Return all benefits to match signing bonus behavior (including approved/rejected)
    const query: any = {};

    const pendingBenefits = await this.terminationResignationModel
      .find(query)
      .populate('employeeId', 'name email position department')
      .sort({ createdAt: -1 });

    return {
      count: pendingBenefits.length,
      benefits: pendingBenefits,
    };
  }
}


@Injectable()
export class PayrollInitiationService {
  constructor(
    @InjectModel(payrollRuns.name)
    private readonly payrollRunsModel: Model<payrollRuns>,
  ) {}

  /**
   * Validate payroll period before initiation
   * Checks for overlapping periods, valid dates, and business rules
   */
  async validatePayrollPeriod(dto: ValidatePeriodDto) {
    const startDate = new Date(dto.startDate);
    const endDate = new Date(dto.endDate);

    // Validation 1: End date must be after start date
    if (endDate <= startDate) {
      throw new BadRequestException('End date must be after start date');
    }

    // Validation 2: Period length must match payroll type
    const daysDiff = Math.ceil((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24));
    
    if (dto.payPeriodType === 'Weekly' && daysDiff !== 7) {
      throw new BadRequestException('Weekly payroll must be exactly 7 days');
    }
    
    if (dto.payPeriodType === 'Bi-Weekly' && daysDiff !== 14) {
      throw new BadRequestException('Bi-weekly payroll must be exactly 14 days');
    }
    
    if (dto.payPeriodType === 'Monthly' && (daysDiff < 28 || daysDiff > 31)) {
      throw new BadRequestException('Monthly payroll must be between 28-31 days');
    }

    // Validation 3: Check for overlapping payroll periods
    const overlappingRun = await this.payrollRunsModel.findOne({
      payrollPeriod: { $gte: startDate, $lte: endDate },
      status: { $nin: ['cancelled', 'deleted'] },
    });

    if (overlappingRun) {
      throw new ConflictException(
        `Overlapping payroll period found: ${overlappingRun.payrollPeriod.toISOString()}`
      );
    }

    // Validation 4: Cannot create payroll for future periods (more than 7 days ahead)
    const today = new Date();
    const maxFutureDate = new Date(today.getTime() + 7 * 24 * 60 * 60 * 1000);
    
    if (startDate > maxFutureDate) {
      throw new BadRequestException('Cannot create payroll more than 7 days in advance');
    }

    return {
      valid: true,
      message: 'Payroll period is valid and ready for initiation',
      periodDetails: {
        startDate,
        endDate,
        duration: daysDiff,
        payPeriodType: dto.payPeriodType,
      },
    };
  }

  /**
   * Initiate new payroll run
   * Creates a new payroll cycle with initial status
   */
  async initiatePayrollRun(dto: InitiatePayrollDto2) {
    // First validate the period
    await this.validatePayrollPeriod({
      startDate: new Date(dto.periodStart),
      endDate: new Date(dto.periodEnd),
      payPeriodType: dto.payPeriodType,
    });

    // Create new payroll run
    const runIdNumber = await this.payrollRunsModel.countDocuments() + 1;
    const runIdFormatted = `PR-${new Date().getFullYear()}-${runIdNumber.toString().padStart(4, '0')}`;
    
    const newPayrollRun = new this.payrollRunsModel({
      runId: runIdFormatted,
      payrollPeriod: new Date(dto.periodEnd),
      status: 'draft',
      entity: 'Company Name', // TODO: Get from configuration
      employees: 0,
      exceptions: 0,
      totalnetpay: 0,
      payrollSpecialistId: dto.initiatorId,
      paymentStatus: 'pending',
    });

    const savedRun = await newPayrollRun.save();

    return {
      message: 'Payroll run initiated successfully',
      runId: savedRun._id,
      run: savedRun,
    };
  }

  /**
   * Get payroll run status
   * Retrieves current status and details of a payroll run
   */
  async getPayrollRunStatus(runId: string) {
    const run = await this.payrollRunsModel.findById(runId);

    if (!run) {
      throw new NotFoundException(`Payroll run with ID ${runId} not found`);
    }

    return {
      runId: run.runId,
      status: run.status,
      payrollPeriod: run.payrollPeriod,
      entity: run.entity,
      totalEmployees: run.employees,
      exceptions: run.exceptions,
      totalNetPay: run.totalnetpay,
      paymentStatus: run.paymentStatus,
      payrollSpecialistId: run.payrollSpecialistId,
      payrollManagerId: run.payrollManagerId,
      financeStaffId: run.financeStaffId,
    };
  }

  /**
   * Edit payroll initiation details
   * Allows modification of payroll period before processing begins
   */
  async editPayrollInitiation(dto: EditPayrollInitiationDto, editorId: string) {
    const run = await this.payrollRunsModel.findById(dto.runId);

    if (!run) {
      throw new NotFoundException(`Payroll run with ID ${dto.runId} not found`);
    }

    // Can only edit if status is 'draft'
    if (run.status !== 'draft') {
      throw new BadRequestException(
        `Cannot edit payroll run with status: ${run.status}. Only draft runs can be edited.`
      );
    }

    const updateData: any = {};

    // Validate and update period date if provided
    if (dto.periodEnd) {
      const newEnd = new Date(dto.periodEnd);
      const newStart = dto.periodStart ? new Date(dto.periodStart) : new Date(newEnd.getFullYear(), newEnd.getMonth(), 1);

      // Validate new period
      await this.validatePayrollPeriod({
        startDate: newStart,
        endDate: newEnd,
        payPeriodType: dto.payPeriodType || 'Monthly',
      });

      updateData.payrollPeriod = newEnd;
    }

    const updatedRun = await this.payrollRunsModel.findByIdAndUpdate(
      dto.runId,
      updateData,
      { new: true }
    );

    return {
      message: 'Payroll initiation updated successfully',
      run: updatedRun,
    };
  }

  /**
   * Start automatic processing of payroll initiation
   * Triggers Phase 0 (bonus/benefit approvals) and prepares for Phase 1
   */
  async startAutomaticProcessing(runId: string, initiatorId: string) {
    const run = await this.payrollRunsModel.findById(runId);

    if (!run) {
      throw new NotFoundException(`Payroll run with ID ${runId} not found`);
    }

    if (run.status !== 'draft') {
      throw new BadRequestException(
        `Cannot start processing. Current status: ${run.status}`
      );
    }

    // Update status to processing
    const updatedRun = await this.payrollRunsModel.findByIdAndUpdate(
      runId,
      {
        status: 'in_progress',
      },
      { new: true }
    );

    return {
      message: 'Automatic payroll processing started',
      run: updatedRun,
      nextSteps: [
        'System will auto-process signing bonuses',
        'System will auto-process termination benefits',
        'System will auto-process resignation benefits',
        'Review and approve all benefits before proceeding to Phase 1',
      ],
    };
  }

  /**
   * Get all payroll runs with optional filtering
   */
  async getAllPayrollRuns(status?: string) {
    const query: any = {};
    
    if (status) query.status = status;

    const runs = await this.payrollRunsModel
      .find(query)
      .sort({ createdAt: -1 });

    return {
      count: runs.length,
      runs,
    };
  }

  /**
   * Delete/Cancel payroll run
   * Can only delete runs that haven't been locked or published
   */
  async deletePayrollRun(runId: string, deleterId: string) {
    const run = await this.payrollRunsModel.findById(runId);

    if (!run) {
      throw new NotFoundException(`Payroll run with ID ${runId} not found`);
    }

    if (['approved', 'published', 'paid'].includes(run.status)) {
      throw new BadRequestException(
        `Cannot delete payroll run with status: ${run.status}`
      );
    }

    await this.payrollRunsModel.findByIdAndDelete(runId);

    return {
      message: 'Payroll run deleted successfully',
    };
  }
}