import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import PDFDocument from 'pdfkit';
import { payrollRuns } from './models/payrollRuns.schema';
import { PayRollStatus, PayRollPaymentStatus, BankStatus, PaySlipPaymentStatus } from './enums/payroll-execution-enum';
import { EmployeeProfile } from '../employee-profile/models/employee-profile.schema';
import { payGrade } from '../payroll-configuration/models/payGrades.schema';
import { allowance } from '../payroll-configuration/models/allowance.schema';
import { taxRules } from '../payroll-configuration/models/taxRules.schema';
import { insuranceBrackets } from '../payroll-configuration/models/insuranceBrackets.schema';
import { payrollPolicies } from '../payroll-configuration/models/payrollPolicies.schema';
import { employeePayrollDetails } from './models/employeePayrollDetails.schema';
import { paySlip } from './models/payslip.schema';
import { ConfigStatus, PolicyType, Applicability } from '../payroll-configuration/enums/payroll-configuration-enums';
import { EmployeeStatus, WorkType } from '../employee-profile/enums/employee-profile.enums';

@Injectable()
export class PayrollExecutionService {
  constructor(
    @InjectModel(payrollRuns.name) private payrollRunsModel: Model<payrollRuns>,
    @InjectModel(EmployeeProfile.name) private employeeProfileModel: Model<EmployeeProfile>,
    @InjectModel(payGrade.name) private payGradeModel: Model<payGrade>,
    @InjectModel(allowance.name) private allowanceModel: Model<allowance>,
    @InjectModel(taxRules.name) private taxRulesModel: Model<taxRules>,
    @InjectModel(insuranceBrackets.name) private insuranceBracketsModel: Model<insuranceBrackets>,
    @InjectModel(payrollPolicies.name) private payrollPoliciesModel: Model<payrollPolicies>,
    @InjectModel(employeePayrollDetails.name) private employeePayrollDetailsModel: Model<employeePayrollDetails>,
    @InjectModel(paySlip.name) private paySlipModel: Model<paySlip>,
  ) {}

  async initiatePayroll(
    payrollPeriod: Date,
    entity: string,
    payrollSpecialistId: string,
  ): Promise<payrollRuns> {
    const year = payrollPeriod.getFullYear();
    const month = payrollPeriod.getMonth() + 1;
    
    // Check if a payroll run already exists for this period and entity
    const existingRun = await this.payrollRunsModel
      .findOne({
        payrollPeriod: {
          $gte: new Date(year, month - 1, 1),
          $lt: new Date(year, month, 1),
        },
        entity,
      })
      .exec();

    if (existingRun) {
      throw new BadRequestException(
        `A payroll run already exists for ${year}-${String(month).padStart(2, '0')} for entity ${entity}. Only one payroll run per month is allowed. Run ID: ${existingRun.runId}`,
      );
    }

    const monthStr = String(month).padStart(2, '0');
    const lastRun = await this.payrollRunsModel
      .findOne({ runId: new RegExp(`^PR-${year}-${monthStr}-`) })
      .sort({ runId: -1 })
      .exec();
    
    const sequence = lastRun 
      ? parseInt(lastRun.runId.split('-')[3] || '0', 10) + 1 
      : 1;
    const runId = `PR-${year}-${monthStr}-${String(sequence).padStart(4, '0')}`;

    const payrollRun = new this.payrollRunsModel({
      runId,
      payrollPeriod,
      status: PayRollStatus.DRAFT,
      entity,
      employees: 0,
      exceptions: 0,
      totalnetpay: 0,
      payrollSpecialistId: new Types.ObjectId(payrollSpecialistId) as any,
      paymentStatus: PayRollPaymentStatus.PENDING,
      payrollManagerId: new Types.ObjectId(payrollSpecialistId) as any, // Set initially to specialist, will be updated when manager approves
    });

    return payrollRun.save();
  }

  async autoGenerateDraftPayrollRun(
    payrollPeriod: Date,
    entity: string,
    payrollSpecialistId: string,
  ): Promise<payrollRuns> {
    const year = payrollPeriod.getFullYear();
    const month = payrollPeriod.getMonth() + 1;

    // Check if a payroll run already exists for this period and entity
    const existingRun = await this.payrollRunsModel
      .findOne({
        payrollPeriod: {
          $gte: new Date(year, month - 1, 1),
          $lt: new Date(year, month, 1),
        },
        entity,
      })
      .exec();

    if (existingRun) {
      throw new BadRequestException(
        `A payroll run already exists for ${year}-${String(month).padStart(2, '0')} for entity ${entity}. Only one payroll run per month is allowed. Run ID: ${existingRun.runId}`,
      );
    }

    // Create the draft payroll run directly (don't call initiatePayroll to avoid double-checking)
    const monthStr = String(month).padStart(2, '0');
    const lastRun = await this.payrollRunsModel
      .findOne({ runId: new RegExp(`^PR-${year}-${monthStr}-`) })
      .sort({ runId: -1 })
      .exec();
    
    const sequence = lastRun 
      ? parseInt(lastRun.runId.split('-')[3] || '0', 10) + 1 
      : 1;
    const runId = `PR-${year}-${monthStr}-${String(sequence).padStart(4, '0')}`;

    const payrollRun = new this.payrollRunsModel({
      runId,
      payrollPeriod,
      status: PayRollStatus.DRAFT,
      entity,
      employees: 0,
      exceptions: 0,
      totalnetpay: 0,
      payrollSpecialistId: new Types.ObjectId(payrollSpecialistId) as any,
      paymentStatus: PayRollPaymentStatus.PENDING,
      payrollManagerId: new Types.ObjectId(payrollSpecialistId) as any,
    });

    return payrollRun.save();
  }

  async autoGenerateDraftPayrollForCurrentPeriod(
    entity: string,
    payrollSpecialistId: string,
  ): Promise<payrollRuns> {
    // Get the last day of the current month
    const now = new Date();
    const lastDayOfMonth = new Date(now.getFullYear(), now.getMonth() + 1, 0);

    return this.autoGenerateDraftPayrollRun(lastDayOfMonth, entity, payrollSpecialistId);
  }

  async getPayrollRunsForReview(): Promise<payrollRuns[]> {
    return this.payrollRunsModel
      .find({
        status: PayRollStatus.DRAFT,
      })
      .populate('payrollSpecialistId')
      .sort({ createdAt: -1 })
      .exec();
  }

  async getPayrollRunsPendingManagerApproval(): Promise<payrollRuns[]> {
    return this.payrollRunsModel
      .find({
        status: PayRollStatus.UNDER_REVIEW,
      })
      .populate('payrollSpecialistId')
      .sort({ createdAt: -1 })
      .exec();
  }

  async getPayrollRunsPendingFinanceApproval(): Promise<payrollRuns[]> {
    return this.payrollRunsModel
      .find({
        status: { $in: [PayRollStatus.UNDER_REVIEW, PayRollStatus.PENDING_FINANCE_APPROVAL] },
      })
      .populate('payrollSpecialistId')
      .populate('payrollManagerId')
      .sort({ createdAt: -1 })
      .exec();
  }

  async getApprovedAndLockedRuns(): Promise<payrollRuns[]> {
    return this.payrollRunsModel
      .find({
        status: { $in: [PayRollStatus.APPROVED, PayRollStatus.LOCKED] },
      })
      .populate('payrollSpecialistId')
      .populate('payrollManagerId')
      .populate('financeStaffId')
      .sort({ createdAt: -1 })
      .exec();
  }

  async getPayrollRunById(payrollRunId: string): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel
      .findById(payrollRunId)
      .populate('payrollSpecialistId')
      .populate('payrollManagerId')
      .populate('financeStaffId')
      .exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    return payrollRun;
  }

  async approvePayroll(
    payrollRunId: string,
    payrollSpecialistId: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.DRAFT) {
      throw new BadRequestException(
        `Cannot approve payroll run with status: ${payrollRun.status}. Only DRAFT payroll runs can be approved.`,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'approve payroll run');

    // Validate that payroll has been calculated (has employees)
    if (payrollRun.employees === 0) {
      throw new BadRequestException('Cannot approve payroll run with no employees. Please calculate payroll first.');
    }

    // Specialist approves: DRAFT → UNDER_REVIEW
    // Manager fields will be set when manager approves
    payrollRun.status = PayRollStatus.UNDER_REVIEW;

    return payrollRun.save();
  }

  async rejectPayroll(
    payrollRunId: string,
    rejectionReason: string,
    payrollSpecialistId: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.DRAFT) {
      throw new BadRequestException(
        `Cannot reject payroll run with status: ${payrollRun.status}. Only DRAFT payroll runs can be rejected.`,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'reject payroll run');

    payrollRun.status = PayRollStatus.REJECTED;
    payrollRun.rejectionReason = rejectionReason;

    return payrollRun.save();
  }

  async managerApprove(
    payrollRunId: string,
    managerId: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.UNDER_REVIEW) {
      throw new BadRequestException(
        `Cannot approve payroll run with status: ${payrollRun.status}. Only payroll runs UNDER_REVIEW can be approved by manager.`,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'approve payroll run as manager');

    payrollRun.status = PayRollStatus.PENDING_FINANCE_APPROVAL;
    payrollRun.managerApprovalDate = new Date();
    payrollRun.payrollManagerId = new Types.ObjectId(managerId) as any;

    return payrollRun.save();
  }

  async managerReject(
    payrollRunId: string,
    managerId: string,
    rejectionReason: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.UNDER_REVIEW) {
      throw new BadRequestException(
        `Cannot reject payroll run with status: ${payrollRun.status}. Only payroll runs UNDER_REVIEW can be rejected by manager.`,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'reject payroll run as manager');

    payrollRun.status = PayRollStatus.REJECTED;
    payrollRun.rejectionReason = rejectionReason;
    payrollRun.payrollManagerId = new Types.ObjectId(managerId) as any;

    return payrollRun.save();
  }

  async financeApprove(
    payrollRunId: string,
    financeStaffId: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.PENDING_FINANCE_APPROVAL) {
      throw new BadRequestException(
        `Cannot approve payroll run with status: ${payrollRun.status}. Only payroll runs PENDING_FINANCE_APPROVAL can be approved by finance.`,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'approve payroll run as finance');

    // Additional validation: Ensure manager has approved
    if (!payrollRun.managerApprovalDate || !payrollRun.payrollManagerId) {
      throw new BadRequestException(
        'Cannot approve payroll run. Manager approval is required before finance approval.',
      );
    }

    // Additional validation: Check for critical irregularities
    const employeeDetails = await this.employeePayrollDetailsModel
      .find({ payrollRunId: payrollRun._id })
      .exec();

    const criticalIssues = employeeDetails.filter(
      (detail) =>
        detail.netSalary < 0 ||
        detail.bankStatus === BankStatus.MISSING ||
        (detail.exceptions && detail.exceptions.includes('Negative net pay')),
    );

    if (criticalIssues.length > 0) {
      throw new BadRequestException(
        `Cannot approve payroll run. Found ${criticalIssues.length} employee(s) with critical issues (negative net pay or missing bank accounts). Please resolve these issues before approval.`,
      );
    }

    payrollRun.status = PayRollStatus.APPROVED;
    payrollRun.paymentStatus = PayRollPaymentStatus.PENDING;
    payrollRun.financeApprovalDate = new Date();
    payrollRun.financeStaffId = new Types.ObjectId(financeStaffId) as any;

    return payrollRun.save();
  }

  async financeReject(
    payrollRunId: string,
    financeStaffId: string,
    rejectionReason: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.PENDING_FINANCE_APPROVAL) {
      throw new BadRequestException(
        `Cannot reject payroll run with status: ${payrollRun.status}. Only payroll runs PENDING_FINANCE_APPROVAL can be rejected by finance.`,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'reject payroll run as finance');

    payrollRun.status = PayRollStatus.REJECTED;
    payrollRun.rejectionReason = rejectionReason;
    payrollRun.financeStaffId = new Types.ObjectId(financeStaffId) as any;

    return payrollRun.save();
  }

  /**
   * Helper method to check if a payroll run is locked
   */
  private isPayrollLocked(payrollRun: payrollRuns): boolean {
    return payrollRun.status === PayRollStatus.LOCKED;
  }

  /**
   * Helper method to validate that payroll run is not locked before making changes
   */
  private validatePayrollNotLocked(payrollRun: payrollRuns, operation: string): void {
    if (this.isPayrollLocked(payrollRun)) {
      throw new BadRequestException(
        `Cannot ${operation}. Payroll run ${payrollRun.runId} is locked and cannot be modified. Please unlock it first if you need to make changes.`,
      );
    }
  }

  /**
   * Lock a finalized payroll run to prevent unauthorized retroactive changes
   * Only Payroll Managers can lock payroll runs
   */
  async lockPayrollRun(
    payrollRunId: string,
    managerId: string,
    lockReason: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    // managerId may come from different auth providers; ensure it's a non-empty string
    if (!managerId || typeof managerId !== 'string' || managerId.trim().length === 0) {
      throw new BadRequestException('Manager identity missing or invalid');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    // Only APPROVED payroll runs can be locked (finalized payrolls)
    if (payrollRun.status !== PayRollStatus.APPROVED) {
      throw new BadRequestException(
        `Cannot lock payroll run with status: ${payrollRun.status}. Only APPROVED payroll runs can be locked.`,
      );
    }

    // Check if already locked
    if (this.isPayrollLocked(payrollRun)) {
      throw new BadRequestException(
        `Payroll run ${payrollRun.runId} is already locked.`,
      );
    }

    payrollRun.status = PayRollStatus.LOCKED;
    // Store lock reason in unlockReason field (reusing existing field)
    payrollRun.unlockReason = `LOCKED: ${lockReason}`;

    return payrollRun.save();
  }

 
  async unlockPayrollRun(
    payrollRunId: string,
    managerId: string,
    unlockReason: string,
  ): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    if (!Types.ObjectId.isValid(managerId)) {
      throw new BadRequestException('Invalid manager ID');
    }

    // Validate unlock reason is substantial (at least 20 characters)
    if (!unlockReason || unlockReason.trim().length < 20) {
      throw new BadRequestException(
        'Unlock reason must be at least 20 characters to properly document the exceptional circumstances requiring this unlock.',
      );
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    // Only LOCKED payroll runs can be unlocked
    if (!this.isPayrollLocked(payrollRun)) {
      throw new BadRequestException(
        `Cannot unlock payroll run with status: ${payrollRun.status}. Only LOCKED payroll runs can be unlocked.`,
      );
    }

    // Return to APPROVED status to allow modifications
    payrollRun.status = PayRollStatus.APPROVED;
    // Store the unlock reason with timestamp for audit trail
    const timestamp = new Date().toISOString();
    payrollRun.unlockReason = `[UNLOCKED ${timestamp}] ${unlockReason}`;

    return payrollRun.save();
  }

  async calculatePayroll(payrollRunId: string): Promise<payrollRuns> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    if (payrollRun.status !== PayRollStatus.DRAFT) {
      throw new BadRequestException(
        `Cannot calculate payroll for run with status: ${payrollRun.status}. Only DRAFT payroll runs can be calculated.`,
      );
    }

    this.validatePayrollNotLocked(payrollRun, 'calculate payroll');

    // Get all active employees for the payroll period
    const payrollPeriodStart = new Date(payrollRun.payrollPeriod);
    payrollPeriodStart.setDate(1); // First day of the month
    
    // Set end to last day of the month
    const payrollPeriodEnd = new Date(payrollRun.payrollPeriod);
    payrollPeriodEnd.setMonth(payrollPeriodEnd.getMonth() + 1);
    payrollPeriodEnd.setDate(0); // Last day of previous month

    const activeEmployees = await this.employeeProfileModel
      .find({
        status: EmployeeStatus.ACTIVE,
        dateOfHire: { $lte: payrollPeriodEnd },
        $or: [
          { contractEndDate: { $gte: payrollPeriodStart } },
          { contractEndDate: { $exists: false } },
        ],
      })
      .populate('payGradeId')
      .exec();

    // Get all configuration rules (don't filter by status - use what's available)
    const [approvedAllowances, approvedTaxRules, approvedInsuranceBrackets] = await Promise.all([
      this.allowanceModel.find({}).exec(),
      this.taxRulesModel.find({}).exec(),
      this.insuranceBracketsModel.find({}).exec(),
    ]);

    const approvedPolicies = await this.payrollPoliciesModel
      .find({
        effectiveDate: { $lte: payrollPeriodEnd },
        policyType: PolicyType.DEDUCTION, // Only statutory deduction policies
      })
      .exec();

    let totalNetPay = 0;
    let totalExceptions = 0;
    const employeePayrollDetailsList: any[] = [];

    // Calculate payroll for each employee
    for (const employee of activeEmployees) {
      try {
        const calculation = await this.calculateEmployeePayroll(
          employee,
          payrollRun._id as Types.ObjectId,
          approvedAllowances,
          approvedTaxRules,
          approvedInsuranceBrackets,
          approvedPolicies,
          payrollPeriodStart,
          payrollPeriodEnd,
        );

        employeePayrollDetailsList.push(calculation.employeePayrollDetail.toObject());
        totalNetPay += calculation.netPay;
        if (calculation.exceptions) {
          totalExceptions++;
        }
      } catch (error: any) {
        totalExceptions++;
        // Create a payroll detail with exception
        const exceptionDetail = {
          employeeId: new Types.ObjectId(employee.id || employee._id),
          payrollRunId: payrollRun._id,
          baseSalary: 0,
          allowances: 0,
          deductions: 0,
          netSalary: 0,
          netPay: 0,
          bankStatus: BankStatus.MISSING,
          exceptions: `Calculation error: ${error?.message || 'Unknown error'}`,
        };
        employeePayrollDetailsList.push(exceptionDetail);
      }
    }

    // Save all employee payroll details
    if (employeePayrollDetailsList.length > 0) {
      await this.employeePayrollDetailsModel.insertMany(employeePayrollDetailsList);
    }

    // Update payroll run totals
    payrollRun.employees = activeEmployees.length;
    payrollRun.exceptions = totalExceptions;
    payrollRun.totalnetpay = totalNetPay;

    return payrollRun.save();
  }

  async getPayrollPreview(payrollRunId: string): Promise<any> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel
      .findById(payrollRunId)
      .populate('payrollSpecialistId')
      .exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    // Get all employee payroll details for this run
    const employeeDetails = await this.employeePayrollDetailsModel
      .find({ payrollRunId: payrollRun._id })
      .populate('employeeId')
      .sort({ netPay: -1 })
      .exec();

    // Calculate summary statistics
    const totalEmployees = employeeDetails.length;
    const employeesWithExceptions = employeeDetails.filter((d) => d.exceptions).length;
    const totalBaseSalary = employeeDetails.reduce((sum, d) => sum + d.baseSalary, 0);
    const totalAllowances = employeeDetails.reduce((sum, d) => sum + d.allowances, 0);
    const totalDeductions = employeeDetails.reduce((sum, d) => sum + d.deductions, 0);
    const totalNetPay = employeeDetails.reduce((sum, d) => sum + d.netPay, 0);
    const employeesWithMissingBank = employeeDetails.filter(
      (d) => d.bankStatus === BankStatus.MISSING,
    ).length;
    const employeesWithNegativePay = employeeDetails.filter((d) => d.netSalary < 0).length;

    // Format employee details for preview
    const employeeList = employeeDetails.map((detail) => {
      const employee = detail.employeeId as any;
      return {
        employeePayrollDetailId: detail._id,
        employeeId: detail.employeeId,
        employeeNumber: employee?.employeeNumber || 'N/A',
        employeeName: employee
          ? `${employee.firstName || ''} ${employee.lastName || ''}`.trim()
          : 'N/A',
        baseSalary: detail.baseSalary,
        allowances: detail.allowances,
        deductions: detail.deductions,
        netSalary: detail.netSalary,
        netPay: detail.netPay,
        bankStatus: detail.bankStatus,
        exceptions: detail.exceptions,
        hasIrregularities: !!detail.exceptions || detail.netSalary < 0 || detail.bankStatus === BankStatus.MISSING,
      };
    });

    return {
      payrollRun: {
        runId: payrollRun.runId,
        payrollPeriod: payrollRun.payrollPeriod,
        status: payrollRun.status,
        entity: payrollRun.entity,
      
      },
      summary: {
        totalEmployees,
        employeesWithExceptions,
        employeesWithMissingBank,
        employeesWithNegativePay,
        totalBaseSalary,
        totalAllowances,
        totalDeductions,
        totalNetPay,
      },
      employees: employeeList,
      irregularities: employeeList.filter((e) => e.hasIrregularities),
    };
  }

  private async calculateEmployeePayroll(
    employee: any,
    payrollRunId: Types.ObjectId,
    approvedAllowances: allowance[],
    approvedTaxRules: taxRules[],
    approvedInsuranceBrackets: insuranceBrackets[],
    approvedPolicies: payrollPolicies[],
    payrollPeriodStart: Date,
    payrollPeriodEnd: Date,
  ): Promise<{
    employeePayrollDetail: any;
    netPay: number;
    exceptions?: string;
  }> {
    const irregularities: string[] = [];
    const employeeId = new Types.ObjectId(employee.id || (employee as any)._id);
    
    // Get base salary from pay grade
    let baseSalary = 0;
    if (employee.payGradeId) {
      if (typeof employee.payGradeId === 'object' && employee.payGradeId.baseSalary) {
        // Already populated
        baseSalary = employee.payGradeId.baseSalary;
      } else {
        // Need to fetch
        const payGradeDoc = await this.payGradeModel.findById(employee.payGradeId).exec();
        if (payGradeDoc) {
          baseSalary = payGradeDoc.baseSalary || 0;
        }
      }
    }

    if (baseSalary === 0) {
      irregularities.push('No pay grade assigned or pay grade has 0 salary');
    }

    // Calculate proration for mid-month hires and terminations
    const prorationInfo = this.calculateProration(
      employee.dateOfHire,
      employee.contractEndDate,
      employee.status,
      employee.statusEffectiveFrom,
      payrollPeriodStart,
      payrollPeriodEnd,
    );

    // Apply proration to base salary
    if (prorationInfo.isProrated) {
      baseSalary = baseSalary * prorationInfo.prorationFactor;
      irregularities.push(
        `Prorated salary: ${prorationInfo.daysWorked} days worked out of ${prorationInfo.totalDays} days (${(prorationInfo.prorationFactor * 100).toFixed(1)}%)`,
      );
    }

    // Check for sudden salary spike (compare with previous payroll run)
    const previousPayroll = await this.employeePayrollDetailsModel
      .findOne({ employeeId })
      .sort({ createdAt: -1 })
      .exec();

    if (previousPayroll && previousPayroll.baseSalary > 0) {
      const salaryIncrease = ((baseSalary - previousPayroll.baseSalary) / previousPayroll.baseSalary) * 100;
      if (salaryIncrease > 20) {
        irregularities.push(`Sudden salary spike detected: ${salaryIncrease.toFixed(1)}% increase from previous period`);
      }
    }

    // Calculate allowances (sum of all approved allowances) - also prorated
    let totalAllowances = approvedAllowances.reduce((sum, a) => sum + (a.amount || 0), 0);
    if (prorationInfo.isProrated) {
      totalAllowances = totalAllowances * prorationInfo.prorationFactor;
    }

    // Calculate gross salary
    const grossSalary = baseSalary + totalAllowances;

    // Calculate statutory deductions (automatically applied for compliance)
    let totalDeductions = 0;
    const statutoryDeductions: { name: string; amount: number; type: string }[] = [];

    // 1. Income Tax (statutory)
    for (const taxRule of approvedTaxRules) {
      const taxAmount = (grossSalary * taxRule.rate) / 100;
      totalDeductions += taxAmount;
      statutoryDeductions.push({
        name: taxRule.name || 'Income Tax',
        amount: taxAmount,
        type: 'Income Tax',
      });
    }

    // 2. Pension / Insurance Contributions (statutory) based on insurance brackets
    //    Deduction is computed on BASE SALARY and only for the bracket that matches the base salary range.
    for (const insurance of approvedInsuranceBrackets) {
      if (baseSalary >= insurance.minSalary && baseSalary <= insurance.maxSalary) {
        const insuranceName = insurance.name.toLowerCase();
        const isPension = insuranceName.includes('pension') || insuranceName.includes('retirement');
        
        const employeeContribution = (baseSalary * insurance.employeeRate) / 100;
        totalDeductions += employeeContribution;
        statutoryDeductions.push({
          name: insurance.name,
          amount: employeeContribution,
          type: isPension ? 'Pension' : 'Insurance',
        });
      }
    }

    // 3. Social Insurance / Health Insurance (statutory)
    // Already handled above in insurance brackets, but we ensure all are applied

    // 4. Labor Law Deductions (statutory) - from approved policies with DEDUCTION type
    for (const policy of approvedPolicies) {
      if (this.isStatutoryPolicyApplicable(policy, employee, payrollPeriodEnd)) {
        const rule = policy.ruleDefinition;
        if (rule && grossSalary >= rule.thresholdAmount) {
          const policyAmount = (grossSalary * rule.percentage) / 100 + rule.fixedAmount;
          totalDeductions += policyAmount;
          statutoryDeductions.push({
            name: policy.policyName,
            amount: policyAmount,
            type: 'Labor Law Deduction',
          });
        }
      }
    }

    // Calculate net pay
    const netSalary = grossSalary - totalDeductions;
    const netPay = Math.max(0, netSalary);

    // Flag negative net pay
    if (netSalary < 0) {
      irregularities.push(`Negative net pay: ${netSalary.toFixed(2)}`);
    }

    // Check for missing bank account
    // TODO: Add actual bank account validation when bank details schema is available
    // For now, we'll default to VALID but flag if validation is needed
    let bankStatus = BankStatus.VALID;
    
    // If net pay is positive, bank account should be validated
    // This check should be enhanced when bank details are integrated
    // For now, we'll assume bank details exist (VALID) but this can be changed
    // based on actual bank account validation logic

    const employeePayrollDetail = new this.employeePayrollDetailsModel({
      employeeId,
      payrollRunId,
      baseSalary,
      allowances: totalAllowances,
      deductions: totalDeductions,
      netSalary,
      netPay,
      bankStatus,
      exceptions: irregularities.length > 0 ? irregularities.join('; ') : undefined,
    });

    return {
      employeePayrollDetail,
      netPay,
      exceptions: irregularities.length > 0 ? irregularities.join('; ') : undefined,
    };
  }

  private calculateProration(
    dateOfHire: Date,
    contractEndDate: Date | undefined,
    employeeStatus: string,
    statusEffectiveFrom: Date | undefined,
    payrollPeriodStart: Date,
    payrollPeriodEnd: Date,
  ): {
    isProrated: boolean;
    prorationFactor: number;
    daysWorked: number;
    totalDays: number;
    reason: string;
  } {
    // Calculate total days in the payroll period (month)
    const totalDays = new Date(payrollPeriodEnd.getFullYear(), payrollPeriodEnd.getMonth() + 1, 0).getDate();

    const periodStart = new Date(payrollPeriodStart);
    // normalize to date-only (local) to avoid timezone/time-of-day off-by-one issues
    const toDateOnly = (d: Date) => new Date(d.getFullYear(), d.getMonth(), d.getDate());
    const periodStartDateOnly = toDateOnly(periodStart);
    let effectiveStartDate = toDateOnly(periodStart);
    let effectiveEndDate = toDateOnly(payrollPeriodEnd);

    // Safely parse hire date if provided
    if (dateOfHire) {
      const hireDateRaw = new Date(dateOfHire);
      if (!isNaN(hireDateRaw.getTime())) {
        const hireDate = toDateOnly(hireDateRaw);
        // Only treat as mid-month if hireDate is strictly after the period start date
        if (hireDate.getTime() > periodStartDateOnly.getTime()) effectiveStartDate = hireDate;
      }
    }

    // Check for termination (using statusEffectiveFrom as termination date)
    if (employeeStatus === 'TERMINATED' && statusEffectiveFrom) {
      const terminationDateRaw = new Date(statusEffectiveFrom);
      if (!isNaN(terminationDateRaw.getTime())) {
        const terminationDate = toDateOnly(terminationDateRaw);
        if (terminationDate.getTime() >= periodStartDateOnly.getTime() && terminationDate.getTime() <= effectiveEndDate.getTime()) {
          effectiveEndDate = terminationDate;
        }
      }
    }

    // Check for contract end date
    if (contractEndDate) {
      const contractEndRaw = new Date(contractEndDate);
      if (!isNaN(contractEndRaw.getTime())) {
        const contractEnd = toDateOnly(contractEndRaw);
        if (contractEnd.getTime() >= periodStartDateOnly.getTime() && contractEnd.getTime() <= effectiveEndDate.getTime()) {
          effectiveEndDate = contractEnd;
        }
      }
    }

    // If effective start is after effective end, employee did not work in this period
    if (effectiveStartDate > effectiveEndDate) {
      return {
        isProrated: true,
        prorationFactor: 0,
        daysWorked: 0,
        totalDays,
        reason: 'No work during period',
      };
    }

    // Calculate days worked (inclusive) using date-only values
    const msPerDay = 1000 * 60 * 60 * 24;
    const timeDiff = effectiveEndDate.getTime() - effectiveStartDate.getTime();
    const daysWorked = Math.max(1, Math.floor(timeDiff / msPerDay) + 1);

    const prorationFactor = Math.min(1, daysWorked / totalDays);
    const isProrated = prorationFactor < 1;

    // Determine reason for proration
    let reason = '';
    if (dateOfHire && new Date(dateOfHire) > periodStart) {
      reason = `Mid-month hire`;
    }
    if (
      (employeeStatus === 'TERMINATED' && statusEffectiveFrom && new Date(statusEffectiveFrom) < payrollPeriodEnd) ||
      (contractEndDate && new Date(contractEndDate) < payrollPeriodEnd)
    ) {
      reason = reason ? `${reason}, Mid-month termination` : 'Mid-month termination';
    }

    return {
      isProrated,
      prorationFactor,
      daysWorked,
      totalDays,
      reason: reason || 'Full period',
    };
  }

  private isStatutoryPolicyApplicable(
    policy: payrollPolicies,
    employee: any,
    payrollPeriodEnd: Date,
  ): boolean {
    // Check if policy is effective
    if (policy.effectiveDate > payrollPeriodEnd) {
      return false;
    }

    // Check applicability based on employee type
    switch (policy.applicability) {
      case Applicability.AllEmployees:
        return true;
      case Applicability.FULL_TIME:
        return employee.workType === WorkType.FULL_TIME;
      case Applicability.PART_TIME:
        return employee.workType === WorkType.PART_TIME;
      case Applicability.CONTRACTORS:
        return employee.contractType !== undefined;
      default:
        return false;
    }
  }

  async generatePayslips(payrollRunId: string): Promise<{ generated: number; errors: number }> {
    if (!Types.ObjectId.isValid(payrollRunId)) {
      throw new BadRequestException('Invalid payroll run ID');
    }

    const payrollRun = await this.payrollRunsModel.findById(payrollRunId).exec();

    if (!payrollRun) {
      throw new NotFoundException('Payroll run not found');
    }

    // Allow generation for APPROVED or LOCKED runs. Previously only APPROVED
    // runs were allowed which prevented specialists from generating payslips
    // for runs that had been locked after approvals.
    if (
      payrollRun.status !== PayRollStatus.APPROVED &&
      payrollRun.status !== PayRollStatus.LOCKED
    ) {
      throw new BadRequestException(
        `Payslips can only be generated for APPROVED or LOCKED payroll runs. Current status: ${payrollRun.status}`,
      );
    }

    // If payroll is explicitly marked as locked we still allow generation; keep
    // validation to prevent accidental generation for other statuses.

    // Get all employee payroll details for this run (lean to work with plain objects)
    const employeeDetails = await this.employeePayrollDetailsModel
      .find({ payrollRunId: payrollRun._id })
      .populate('employeeId')
      .lean()
      .exec();

    let generated = 0;
    let errors = 0;
    const errorsDetails: string[] = [];

    // Iterate and create payslips safely
    for (const detail of employeeDetails) {
      try {
        const employeeId = (detail.employeeId && (detail.employeeId as any)._id) ? (detail.employeeId as any)._id : detail.employeeId;

        // Defensive: ensure we have an employeeId and payrollRunId
        if (!employeeId || !payrollRun._id) {
          errors++;
          errorsDetails.push('Missing employeeId or payrollRunId for payroll detail: ' + JSON.stringify(detail._id));
          continue;
        }

        // Skip if payslip already exists
        const existingPayslip = await this.paySlipModel.findOne({ employeeId, payrollRunId: payrollRun._id }).lean().exec();
        if (existingPayslip) continue;

        // Build a minimal, valid payslip payload compatible with schema
        const totalGross = Number((detail.baseSalary || 0) + (detail.allowances || 0) + (detail.bonus || 0) + (detail.benefit || 0));
        const totalDeductions = Number(detail.deductions || 0);
        const netPay = Number(detail.netPay || 0);

        const payslipPayload: any = {
          employeeId: employeeId,
          payrollRunId: payrollRun._id,
          totalGrossSalary: totalGross,
          totaDeductions: totalDeductions,
          netPay: netPay,
          paymentStatus: PaySlipPaymentStatus.PENDING,
        };

        // Attach earningsDetails only if we have useful breakdown
        const earningsDetails: any = {};
        if (typeof detail.baseSalary === 'number') earningsDetails.baseSalary = Number(detail.baseSalary);
        // `earningsDetails.allowances` in the payslip schema is an embedded array.
        // Only attach it when we have a breakdown array; otherwise keep the numeric
        // allowance value on the parent payslip totals to avoid casting errors.
        if (Array.isArray((detail as any).earningsBreakdown) && (detail as any).earningsBreakdown.length > 0) {
          earningsDetails.allowances = (detail as any).earningsBreakdown;
        }
        // Bonuses and benefits are embedded arrays in the schema; only include
        // them when a breakdown is available as arrays.
        if (Array.isArray((detail as any).bonusesBreakdown) && (detail as any).bonusesBreakdown.length > 0) {
          earningsDetails.bonuses = (detail as any).bonusesBreakdown;
        }
        if (Array.isArray((detail as any).benefitsBreakdown) && (detail as any).benefitsBreakdown.length > 0) {
          earningsDetails.benefits = (detail as any).benefitsBreakdown;
        }
        if (Object.keys(earningsDetails).length > 0) payslipPayload.earningsDetails = earningsDetails;

        // Attach deductionsDetails only if available
        const deductionsDetails: any = {};
        if (typeof detail.deductions === 'number' && detail.deductions > 0) deductionsDetails.totalDeductions = Number(detail.deductions);
        if (Object.keys(deductionsDetails).length > 0) payslipPayload.deductionsDetails = deductionsDetails;

        // Create and save payslip
        await this.paySlipModel.create(payslipPayload);
        generated++;
      } catch (err: any) {
        errors++;
        const message = err?.message || String(err);
        console.error('Error generating payslip for detail:', detail?._id, message);
        errorsDetails.push(message);
      }
    }
    // Mark all generated payslips as PAID
        await this.paySlipModel.updateMany(
       { 
        payrollRunId: payrollRun._id, paymentStatus: PaySlipPaymentStatus.PENDING
       },
       {
         $set: { paymentStatus: PaySlipPaymentStatus.PAID 
       } 
      },
);

          // Mark the payroll run as fully paid
      payrollRun.paymentStatus = PayRollPaymentStatus.PAID;
      await payrollRun.save();

    // Return basic stats and sample errors to aid debugging
    return { generated, errors, errorsDetails: errorsDetails.slice(0, 20) } as any;
  }

  async generatePayslipPDF(payslipId: string): Promise<Buffer> {
    if (!Types.ObjectId.isValid(payslipId)) {
      throw new BadRequestException('Invalid payslip ID');
    }

    const payslip = await this.paySlipModel
      .findById(payslipId)
      .populate('employeeId')
      .populate('payrollRunId')
      .exec();

    if (!payslip) {
      throw new NotFoundException('Payslip not found');
    }

    const employee = payslip.employeeId as any;
    const payrollRun = payslip.payrollRunId as any;

    // Create PDF document
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];

    // Collect PDF data
    doc.on('data', (chunk) => chunks.push(chunk));
    
    return new Promise((resolve, reject) => {
      doc.on('end', () => {
        const pdfBuffer = Buffer.concat(chunks);
        resolve(pdfBuffer);
      });

      doc.on('error', reject);

      // Header
      doc.fontSize(20).text('PAYSLIP', { align: 'center' });
      doc.moveDown();

      // Company/Entity Info
      doc.fontSize(14).text(payrollRun?.entity || 'Company Name', { align: 'center' });
      doc.moveDown(0.5);

      // Payroll Period
      const payrollPeriod = payrollRun?.payrollPeriod
        ? new Date(payrollRun.payrollPeriod).toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
          })
        : 'N/A';
      doc.fontSize(12).text(`Pay Period: ${payrollPeriod}`, { align: 'center' });
      doc.moveDown();

      // Employee Information
      doc.fontSize(14).text('Employee Information', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11);
      doc.text(`Employee Number: ${employee?.employeeNumber || 'N/A'}`);
      doc.text(`Name: ${employee?.firstName || ''} ${employee?.lastName || ''}`.trim() || 'N/A');
      if (employee?.workEmail) {
        doc.text(`Email: ${employee.workEmail}`);
      }
      doc.moveDown();



      // Earnings Section
      doc.fontSize(14).text('Earnings', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11);
      
      const earnings = payslip.earningsDetails || {};
      doc.text(`Base Salary: $${(earnings.baseSalary || 0).toFixed(2)}`, { continued: true, align: 'left' });
      
      if (earnings.allowances && Array.isArray(earnings.allowances)) {
        earnings.allowances.forEach((allowance: any) => {
          doc.text(`${allowance.name || 'Allowance'}: $${(allowance.amount || 0).toFixed(2)}`);
        });
      }
      
      if (earnings.bonuses && Array.isArray(earnings.bonuses)) {
        earnings.bonuses.forEach((bonus: any) => {
          doc.text(`Bonus: $${(bonus.amount || 0).toFixed(2)}`);
        });
      }
      
      if (earnings.benefits && Array.isArray(earnings.benefits)) {
        earnings.benefits.forEach((benefit: any) => {
          doc.text(`Benefit: $${(benefit.amount || 0).toFixed(2)}`);
        });
      }

      doc.moveDown();
      doc.fontSize(12).text(`Total Gross Salary: $${payslip.totalGrossSalary.toFixed(2)}`, { align: 'right' });
      doc.moveDown();

      // Deductions Section
      doc.fontSize(14).text('Deductions', { underline: true });
      doc.moveDown(0.5);
      doc.fontSize(11);
      
      const deductions = payslip.deductionsDetails || {};
      const earningsForDeductions = payslip.earningsDetails || {};
      const baseSalaryForDeductions =
        (earningsForDeductions && typeof (earningsForDeductions as any).baseSalary === 'number'
          ? (earningsForDeductions as any).baseSalary
          : payslip.totalGrossSalary) || 0;

      if (deductions.taxes && Array.isArray(deductions.taxes)) {
        deductions.taxes.forEach((tax: any) => {
          const taxAmount = (payslip.totalGrossSalary * (tax.rate || 0)) / 100;
          doc.text(`${tax.name || 'Tax'}: $${taxAmount.toFixed(2)}`);
        });
      }
      
      if (deductions.insurances && Array.isArray(deductions.insurances)) {
        deductions.insurances.forEach((insurance: any) => {
          const insuranceAmount = (baseSalaryForDeductions * (insurance.employeeRate || 0)) / 100;
          doc.text(`${insurance.name || 'Insurance'}: $${insuranceAmount.toFixed(2)}`);
        });
      }

      doc.moveDown();
      doc.fontSize(12).text(`Total Deductions: $${(payslip.totaDeductions || 0).toFixed(2)}`, { align: 'right' });
      doc.moveDown(2);

      // Net Pay
      doc.fontSize(16).text(`NET PAY: $${payslip.netPay.toFixed(2)}`, { align: 'center', underline: true });
      doc.moveDown(2);

      // Footer
      doc.fontSize(10).text('This is a computer-generated payslip.', { align: 'center' });
      doc.text(`Generated on: ${new Date().toLocaleDateString('en-US')}`, { align: 'center' });
      doc.text(`Payslip ID: ${payslipId}`, { align: 'center' });

      // Finalize PDF
      doc.end();
    });
  }

  /**
   * Return payslips for a given payroll run. Accepts either a Mongo ObjectId
   * or a human-friendly runId (e.g., PR-2025-12-0001).
   */
  async getPayslipsForRun(payrollRunId: string): Promise<any[]> {
    let payrollRunObjectId: Types.ObjectId | null = null;

    if (Types.ObjectId.isValid(payrollRunId)) {
      payrollRunObjectId = new Types.ObjectId(payrollRunId);
    } else {
      const run = await this.payrollRunsModel.findOne({ runId: payrollRunId }).exec();
      if (!run) {
        throw new BadRequestException('Invalid payroll run ID');
      }
      payrollRunObjectId = run._id as Types.ObjectId;
    }

    return this.paySlipModel
      .find({ payrollRunId: payrollRunObjectId })
      .populate('employeeId')
      .populate('payrollRunId')
      .sort({ createdAt: -1 })
      .exec();
  }

  /**
   * Escalate an irregularity to Payroll Manager for review
   * Payroll Specialists can escalate irregularities they cannot resolve
   * Uses existing exceptions field to track escalation status
   */
  async escalateIrregularity(
    employeePayrollDetailId: string,
    irregularityDescription: string,
    escalationNotes: string | undefined,
    payrollSpecialistId: string,
  ): Promise<employeePayrollDetails> {
    if (!Types.ObjectId.isValid(employeePayrollDetailId)) {
      throw new BadRequestException('Invalid employee payroll detail ID');
    }

    if (!Types.ObjectId.isValid(payrollSpecialistId)) {
      throw new BadRequestException('Invalid payroll specialist ID');
    }

    // Get the employee payroll detail
    const employeePayrollDetail = await this.employeePayrollDetailsModel
      .findById(employeePayrollDetailId)
      .populate('employeeId')
      .populate('payrollRunId')
      .exec();

    if (!employeePayrollDetail) {
      throw new NotFoundException('Employee payroll detail not found');
    }

    // Check if already escalated (check if exceptions contains ESCALATED marker)
    if (employeePayrollDetail.exceptions && employeePayrollDetail.exceptions.includes('[ESCALATED]')) {
      throw new BadRequestException(
        'This irregularity has already been escalated and is pending resolution.',
      );
    }

    // Append escalation information to exceptions field
    const escalationMarker = `[ESCALATED] ${irregularityDescription}`;
    const escalationInfo = escalationNotes 
      ? ` | Escalation Notes: ${escalationNotes} | Escalated By: ${payrollSpecialistId}`
      : ` | Escalated By: ${payrollSpecialistId}`;
    
    const updatedExceptions = employeePayrollDetail.exceptions
      ? `${employeePayrollDetail.exceptions}; ${escalationMarker}${escalationInfo}`
      : `${escalationMarker}${escalationInfo}`;

    employeePayrollDetail.exceptions = updatedExceptions;

    return employeePayrollDetail.save();
  }

  /**
   * Get all escalated irregularities for Payroll Manager review
   * Finds employeePayrollDetails where exceptions field contains [ESCALATED] marker
   */
  async getEscalatedIrregularities(): Promise<employeePayrollDetails[]> {
    return this.employeePayrollDetailsModel
      .find({
        exceptions: { $regex: /\[ESCALATED\]/, $options: 'i' },
      })
      .populate('employeeId')
      .populate('payrollRunId')
      .sort({ createdAt: -1 })
      .exec();
  }

  /**
   * Get escalated irregularities for a specific payroll run
   */
  async getEscalatedIrregularitiesByPayrollRun(payrollRunId: string): Promise<employeePayrollDetails[]> {
    // Accept either a Mongo ObjectId or a human-friendly runId (e.g., PR-2025-12-0001).
    let payrollRunObjectId: Types.ObjectId | null = null;

    if (Types.ObjectId.isValid(payrollRunId)) {
      payrollRunObjectId = new Types.ObjectId(payrollRunId);
    } else {
      // Try to resolve by runId field on payrollRuns collection
      const run = await this.payrollRunsModel.findOne({ runId: payrollRunId }).exec();
      if (!run) {
        throw new BadRequestException('Invalid payroll run ID');
      }
      payrollRunObjectId = run._id as Types.ObjectId;
    }

    return this.employeePayrollDetailsModel
      .find({
        payrollRunId: payrollRunObjectId,
        exceptions: { $regex: /\[ESCALATED\]/, $options: 'i' },
      })
      .populate('employeeId')
      .populate('payrollRunId')
      .sort({ createdAt: -1 })
      .exec();
  }

  /**
   * Resolve an escalated irregularity
   * Payroll Managers can resolve or dismiss escalated irregularities
   */
  async resolveIrregularity(
    employeePayrollDetailId: string,
    managerId: string,
    resolutionNotes: string,
    status: string,
  ): Promise<employeePayrollDetails> {
    if (!Types.ObjectId.isValid(employeePayrollDetailId)) {
      throw new BadRequestException('Invalid employee payroll detail ID');
    }

    if (!Types.ObjectId.isValid(managerId)) {
      throw new BadRequestException('Invalid manager ID');
    }

    if (status !== 'resolved' && status !== 'dismissed') {
      throw new BadRequestException(
        `Invalid status. Only 'resolved' or 'dismissed' statuses are allowed for resolution.`,
      );
    }

    // Validate resolution notes length
    if (!resolutionNotes || resolutionNotes.trim().length < 10) {
      throw new BadRequestException(
        'Resolution notes must be at least 10 characters to document the decision.',
      );
    }

    const employeePayrollDetail = await this.employeePayrollDetailsModel
      .findById(employeePayrollDetailId)
      .exec();

    if (!employeePayrollDetail) {
      throw new NotFoundException('Employee payroll detail not found');
    }

    // Check if it's escalated
    if (!employeePayrollDetail.exceptions || !employeePayrollDetail.exceptions.includes('[ESCALATED]')) {
      throw new BadRequestException(
        'This irregularity has not been escalated or has already been resolved.',
      );
    }

    // Check if already resolved
    if (employeePayrollDetail.exceptions.includes('[RESOLVED]') || employeePayrollDetail.exceptions.includes('[DISMISSED]')) {
      throw new BadRequestException(
        'This irregularity has already been resolved or dismissed.',
      );
    }

    // Append resolution information to exceptions field
    const resolutionMarker = status === 'resolved' ? '[RESOLVED]' : '[DISMISSED]';
    const resolutionInfo = ` | Resolution: ${resolutionNotes} | Resolved By: ${managerId} | Resolved At: ${new Date().toISOString()}`;
    // Keep the '[ESCALATED]' marker so the record remains visible in the escalated list,
    // but append the resolution marker so the UI can indicate it was resolved/dismissed.
    const updatedExceptions = employeePayrollDetail.exceptions
      ? `${employeePayrollDetail.exceptions}; ${resolutionMarker}${resolutionInfo}`
      : `${resolutionMarker}${resolutionInfo}`;

    employeePayrollDetail.exceptions = updatedExceptions;

    return employeePayrollDetail.save();
  }
}
//. alo 3ayz a3ml pushh