/**
 * File metadata extracted from uploaded file.
 * This is NOT user input - it's generated by the server from the uploaded file.
 */
export interface FileMetadata {
  originalName: string;
  filePath: string;
  fileType: string;
  size: number;
}
